//rp201/index.tsx
'use client';
import React, { useState, useCallback, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import {
  Container,
  Typography,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Button,
  Box,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  TablePagination,
} from '@mui/material';
import Swal from 'sweetalert2';

// สำหรับ Export Excel
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver'; // จำเป็นต้องมีเพื่อให้ไฟล์ดาวน์โหลดได้

// สำหรับ Export PDF
import jsPDF from 'jspdf';
import 'jspdf-autotable';
// หากต้องการใช้ Font ภาษาไทยใน PDF ต้องติดตั้งและตั้งค่า Font เพิ่มเติม
// ตัวอย่าง: npm install jspdf-autotable-font-loader
// import 'jspdf-autotable-font-loader/font/THSarabunNew'; // อย่าลืมติดตั้งและตั้งค่า Font จริงๆ

// --- จำลองคอมโพเนนต์จาก @crema (ถ้าคุณไม่ได้ติดตั้งไลบรารี @crema จริงๆ) ---
const AppCard: React.FC<{ children: React.ReactNode; title?: string; sx?: any }> = ({
  children,
  title,
  sx,
}) => (
  <Paper sx={{ p: 4, ...sx }}>
    {title && <Typography variant="h6" gutterBottom>{title}</Typography>}
    {children}
  </Paper>
);

const AppsContent: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Box sx={{ flexGrow: 1, p: 3 }}>{children}</Box>
);

const AppInfoView: React.FC = () => {
  return null; // จำลอง AppInfoView
};

const IntlMessages: React.FC<{ id: string; defaultMessage?: string }> = ({
  id,
  defaultMessage,
}) => <>{defaultMessage || id}</>;

const useIntl = () => ({
  messages: {
    common_search: 'ค้นหา',
    common_filter: 'ตัวกรอง',
    common_no_data: 'ไม่มีข้อมูลที่ตรงกับเงื่อนไข',
    table_rows_per_page: 'จำนวนแถวต่อหน้า:',
    year_all: 'ทั้งหมด',
    generate_report_button: 'สร้างรายงาน',
    export_excel_button: 'ส่งออกข้อมูลเป็น Excel',
    export_pdf_button: 'ส่งออกข้อมูลเป็น PDF',
    staff_management_title: 'ข้อมูลพื้นฐานบุคลากร (UOC Staff)',
  },
});
// --- สิ้นสุดการจำลอง ---

// --- กำหนดประเภทข้อมูลสำหรับแต่ละแถวในตาราง uoc_staff ---
interface StaffData {
  ds2001_id: number;
  academic_year: string;
  semester: string;
  univ_id: string;
  citizen_id: string;
  prefix_name_id: string;
  stf_fname: string;
  stf_mname: string;
  stf_lname: string;
  stf_fname_en: string;
  stf_mname_en: string;
  stf_lname_en: string;
  gender_id: string;
  birthday: string;
  homeadd: string;
  moo: string;
  street: string;
  sub_district_id: string;
  telephone: string;
  email: string;
  zipcode: string;
  nationality_id: string;
  stafftype_id: string;
  time_contact_id: string;
  budget_id: string;
  substafftype_id: string;
  admin_position_id: string;
  academicstanding_id: string;
  positionlevel_id: string;
  position_id: string;
  position_type_id: string;
  class_id: string;
  class_code: string;
  faculty_id: string;
  department_id: string;
  division_id: string;
  section_id: string;
  work_status_id: string;
  tax_status_id: string;
  salary: string;
  pos_no: string;
  appointed_date: string;
  retired_date: string;
  status_id: string;
}

// --- ข้อมูลจำลอง (Mock Data) สำหรับตาราง uoc_staff ---
// ข้อมูลทั้งหมดจากไฟล์ _DS2001_Staff__202506221953.json
// *** เริ่มข้อมูลประมาณ 40 รายการจากไฟล์ JSON ที่นี่ ***
const allStaffData: StaffData[] = [
  {
    "ds2001_id": 1,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "3659900046195",
    "prefix_name_id": "3",
    "stf_fname": "ธวัชชัย",
    "stf_mname": "",
    "stf_lname": "ศุภดิษฐ์",
    "stf_fname_en": "Tawadchai",
    "stf_mname_en": "",
    "stf_lname_en": "Suppadit",
    "gender_id": "1",
    "birthday": "1968-06-04",
    "homeadd": "91/136",
    "moo": "2",
    "street": "วัดเปรมประชากร",
    "sub_district_id": "130111",
    "telephone": "0811234567",
    "email": "stawadchai@gmail.com",
    "zipcode": "12120",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "1",
    "appointed_date": "2013-05-01",
    "retired_date": "2028-09-30",
    "status_id": "1"
  },
  {
    "ds2001_id": 2,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1659900018501",
    "prefix_name_id": "3",
    "stf_fname": "พิเชษฐ",
    "stf_mname": "",
    "stf_lname": "วิริยะ",
    "stf_fname_en": "Pichet",
    "stf_mname_en": "",
    "stf_lname_en": "Wiriya",
    "gender_id": "1",
    "birthday": "1972-03-24",
    "homeadd": "91",
    "moo": "1",
    "street": "ราชพฤกษ์",
    "sub_district_id": "100401",
    "telephone": "0822345678",
    "email": "pichet.wiriya@hotmail.com",
    "zipcode": "10160",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "2",
    "appointed_date": "2013-05-01",
    "retired_date": "2032-09-30",
    "status_id": "1"
  },
  {
    "ds2001_id": 3,
    "academic_year": "2568",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "3659900046196",
    "prefix_name_id": "3",
    "stf_fname": "สมชาย",
    "stf_mname": "",
    "stf_lname": "ใจดี",
    "stf_fname_en": "Somchai",
    "stf_mname_en": "",
    "stf_lname_en": "Jaidee",
    "gender_id": "1",
    "birthday": "1970-01-01",
    "homeadd": "123",
    "moo": "5",
    "street": "สุขุมวิท",
    "sub_district_id": "101101",
    "telephone": "0813334444",
    "email": "somchai@example.com",
    "zipcode": "10110",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "3",
    "appointed_date": "2015-03-10",
    "retired_date": "2030-01-01",
    "status_id": "1"
  },
  {
    "ds2001_id": 4,
    "academic_year": "2569",
    "semester": "1",
    "univ_id": "2601",
    "citizen_id": "4567890123456",
    "prefix_name_id": "2",
    "stf_fname": "มาลี",
    "stf_mname": "",
    "stf_lname": "งามยิ่ง",
    "stf_fname_en": "Malee",
    "stf_mname_en": "",
    "stf_lname_en": "Namyind",
    "gender_id": "2",
    "birthday": "1980-05-15",
    "homeadd": "45",
    "moo": "3",
    "street": "พระราม 9",
    "sub_district_id": "103101",
    "telephone": "0987654321",
    "email": "malee@example.com",
    "zipcode": "10310",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "4",
    "appointed_date": "2018-07-20",
    "retired_date": "2040-05-15",
    "status_id": "1"
  },
  {
    "ds2001_id": 5,
    "academic_year": "2570",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1489900092222",
    "prefix_name_id": "4",
    "stf_fname": "มะลิวัลย์",
    "stf_mname": "",
    "stf_lname": "สิงห์เสือ",
    "stf_fname_en": "Maliwan",
    "stf_mname_en": "",
    "stf_lname_en": "Singsuea",
    "gender_id": "2",
    "birthday": "1989-02-19",
    "homeadd": "91",
    "moo": "9",
    "street": "-",
    "sub_district_id": "480113",
    "telephone": "0998765432",
    "email": "-",
    "zipcode": "48000",
    "nationality_id": "TH",
    "stafftype_id": "5",
    "time_contact_id": "4",
    "budget_id": "1",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "220",
    "position_type_id": "3",
    "class_id": "3",
    "class_code": "3",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "5",
    "appointed_date": "2020-01-01",
    "retired_date": "2049-02-19",
    "status_id": "1"
  },
  {
    "ds2001_id": 6,
    "academic_year": "2567",
    "semester": "1",
    "univ_id": "2601",
    "citizen_id": "1234567890123",
    "prefix_name_id": "1",
    "stf_fname": "นายแดง",
    "stf_mname": "",
    "stf_lname": "ดำ",
    "stf_fname_en": "Daeng",
    "stf_mname_en": "",
    "stf_lname_en": "Dum",
    "gender_id": "1",
    "birthday": "1975-08-20",
    "homeadd": "789",
    "moo": "10",
    "street": "พหลโยธิน",
    "sub_district_id": "102201",
    "telephone": "0834567890",
    "email": "daeng.dum@example.com",
    "zipcode": "10220",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "6",
    "appointed_date": "2010-01-01",
    "retired_date": "2035-08-20",
    "status_id": "1"
  },
  {
    "ds2001_id": 7,
    "academic_year": "2568",
    "semester": "1",
    "univ_id": "2602",
    "citizen_id": "9876543210987",
    "prefix_name_id": "2",
    "stf_fname": "นางเขียว",
    "stf_mname": "",
    "stf_lname": "ขาว",
    "stf_fname_en": "Khiao",
    "stf_mname_en": "",
    "stf_lname_en": "Khao",
    "gender_id": "2",
    "birthday": "1985-11-01",
    "homeadd": "101",
    "moo": "1",
    "street": "ลาดพร้าว",
    "sub_district_id": "103102",
    "telephone": "0845678901",
    "email": "khiao.khao@example.com",
    "zipcode": "10310",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "7",
    "appointed_date": "2019-04-15",
    "retired_date": "2045-11-01",
    "status_id": "1"
  },
  {
    "ds2001_id": 8,
    "academic_year": "2569",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1122334455667",
    "prefix_name_id": "3",
    "stf_fname": "นายฟ้า",
    "stf_mname": "",
    "stf_lname": "ใส",
    "stf_fname_en": "Fah",
    "stf_mname_en": "",
    "stf_lname_en": "Sai",
    "gender_id": "1",
    "birthday": "1990-03-03",
    "homeadd": "202",
    "moo": "3",
    "street": "รัชดาภิเษก",
    "sub_district_id": "103201",
    "telephone": "0856789012",
    "email": "fah.sai@example.com",
    "zipcode": "10320",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "8",
    "appointed_date": "2021-09-01",
    "retired_date": "2050-03-03",
    "status_id": "1"
  },
  {
    "ds2001_id": 9,
    "academic_year": "2570",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "9988776655443",
    "prefix_name_id": "4",
    "stf_fname": "นางสาวม่วง",
    "stf_mname": "",
    "stf_lname": "ทอง",
    "stf_fname_en": "Muang",
    "stf_mname_en": "",
    "stf_lname_en": "Thong",
    "gender_id": "2",
    "birthday": "1995-12-25",
    "homeadd": "303",
    "moo": "5",
    "street": "เพชรบุรี",
    "sub_district_id": "104101",
    "telephone": "0867890123",
    "email": "muang.thong@example.com",
    "zipcode": "10410",
    "nationality_id": "TH",
    "stafftype_id": "5",
    "time_contact_id": "4",
    "budget_id": "1",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "220",
    "position_type_id": "3",
    "class_id": "3",
    "class_code": "3",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "9",
    "appointed_date": "2023-02-10",
    "retired_date": "2055-12-25",
    "status_id": "1"
  },
  {
    "ds2001_id": 10,
    "academic_year": "2567",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000010",
    "prefix_name_id": "3",
    "stf_fname": "สมศักดิ์",
    "stf_mname": "",
    "stf_lname": "เก่งมาก",
    "stf_fname_en": "Somsak",
    "stf_mname_en": "",
    "stf_lname_en": "Kengmak",
    "gender_id": "1",
    "birthday": "1978-07-11",
    "homeadd": "10",
    "moo": "1",
    "street": "ประชาชื่น",
    "sub_district_id": "101201",
    "telephone": "0871234567",
    "email": "somsak.k@example.com",
    "zipcode": "10120",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "10",
    "appointed_date": "2012-08-01",
    "retired_date": "2038-07-11",
    "status_id": "1"
  },
  {
    "ds2001_id": 11,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000011",
    "prefix_name_id": "2",
    "stf_fname": "สมศรี",
    "stf_mname": "",
    "stf_lname": "รวยมาก",
    "stf_fname_en": "Somsri",
    "stf_mname_en": "",
    "stf_lname_en": "Ruaymak",
    "gender_id": "2",
    "birthday": "1982-01-20",
    "homeadd": "20",
    "moo": "2",
    "street": "รามอินทรา",
    "sub_district_id": "102301",
    "telephone": "0882345678",
    "email": "somsri.r@example.com",
    "zipcode": "10230",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "11",
    "appointed_date": "2016-03-01",
    "retired_date": "2042-01-20",
    "status_id": "1"
  },
  {
    "ds2001_id": 12,
    "academic_year": "2568",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000012",
    "prefix_name_id": "3",
    "stf_fname": "สุชาติ",
    "stf_mname": "",
    "stf_lname": "มีสุข",
    "stf_fname_en": "Suchart",
    "stf_mname_en": "",
    "stf_lname_en": "Meesuk",
    "gender_id": "1",
    "birthday": "1975-04-05",
    "homeadd": "30",
    "moo": "3",
    "street": "พหลโยธิน",
    "sub_district_id": "102401",
    "telephone": "0893456789",
    "email": "suchart.m@example.com",
    "zipcode": "10240",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "12",
    "appointed_date": "2010-09-15",
    "retired_date": "2035-04-05",
    "status_id": "1"
  },
  {
    "ds2001_id": 13,
    "academic_year": "2568",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000013",
    "prefix_name_id": "2",
    "stf_fname": "สุชาดา",
    "stf_mname": "",
    "stf_lname": "โชคดี",
    "stf_fname_en": "Suchada",
    "stf_mname_en": "",
    "stf_lname_en": "Chokdee",
    "gender_id": "2",
    "birthday": "1990-06-10",
    "homeadd": "40",
    "moo": "4",
    "street": "ลาดพร้าว",
    "sub_district_id": "103102",
    "telephone": "0904567890",
    "email": "suchada.c@example.com",
    "zipcode": "10310",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "13",
    "appointed_date": "2018-11-20",
    "retired_date": "2050-06-10",
    "status_id": "1"
  },
  {
    "ds2001_id": 14,
    "academic_year": "2569",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000014",
    "prefix_name_id": "3",
    "stf_fname": "วีระ",
    "stf_mname": "",
    "stf_lname": "รุ่งเรือง",
    "stf_fname_en": "Weera",
    "stf_mname_en": "",
    "stf_lname_en": "Rungruang",
    "gender_id": "1",
    "birthday": "1970-09-01",
    "homeadd": "50",
    "moo": "5",
    "street": "สุขุมวิท",
    "sub_district_id": "101101",
    "telephone": "0915678901",
    "email": "weera.r@example.com",
    "zipcode": "10110",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "14",
    "appointed_date": "2013-02-28",
    "retired_date": "2030-09-01",
    "status_id": "1"
  },
  {
    "ds2001_id": 15,
    "academic_year": "2569",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000015",
    "prefix_name_id": "2",
    "stf_fname": "วิไล",
    "stf_mname": "",
    "stf_lname": "พูนสุข",
    "stf_fname_en": "Wilai",
    "stf_mname_en": "",
    "stf_lname_en": "Poonsuk",
    "gender_id": "2",
    "birthday": "1988-10-10",
    "homeadd": "60",
    "moo": "6",
    "street": "พระราม 9",
    "sub_district_id": "103101",
    "telephone": "0926789012",
    "email": "wilai.p@example.com",
    "zipcode": "10310",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "15",
    "appointed_date": "2020-05-01",
    "retired_date": "2048-10-10",
    "status_id": "1"
  },
  {
    "ds2001_id": 16,
    "academic_year": "2570",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000016",
    "prefix_name_id": "3",
    "stf_fname": "ชาญชัย",
    "stf_mname": "",
    "stf_lname": "มั่นคง",
    "stf_fname_en": "Charnchai",
    "stf_mname_en": "",
    "stf_lname_en": "Mankong",
    "gender_id": "1",
    "birthday": "1973-03-12",
    "homeadd": "70",
    "moo": "7",
    "street": "สุขสวัสดิ์",
    "sub_district_id": "101401",
    "telephone": "0937890123",
    "email": "charnchai.m@example.com",
    "zipcode": "10140",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "16",
    "appointed_date": "2015-06-01",
    "retired_date": "2033-03-12",
    "status_id": "1"
  },
  {
    "ds2001_id": 17,
    "academic_year": "2570",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000017",
    "prefix_name_id": "2",
    "stf_fname": "นันทนา",
    "stf_mname": "",
    "stf_lname": "ใจสงบ",
    "stf_fname_en": "Nantana",
    "stf_mname_en": "",
    "stf_lname_en": "Jaisangob",
    "gender_id": "2",
    "birthday": "1992-07-22",
    "homeadd": "80",
    "moo": "8",
    "street": "งามวงศ์วาน",
    "sub_district_id": "101301",
    "telephone": "0948901234",
    "email": "nantana.j@example.com",
    "zipcode": "10130",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "17",
    "appointed_date": "2022-09-01",
    "retired_date": "2052-07-22",
    "status_id": "1"
  },
  {
    "ds2001_id": 18,
    "academic_year": "2567",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000018",
    "prefix_name_id": "3",
    "stf_fname": "เกรียงไกร",
    "stf_mname": "",
    "stf_lname": "สุขใจ",
    "stf_fname_en": "Kriangkrai",
    "stf_mname_en": "",
    "stf_lname_en": "Sukjai",
    "gender_id": "1",
    "birthday": "1971-05-08",
    "homeadd": "90",
    "moo": "9",
    "street": "วิภาวดีรังสิต",
    "sub_district_id": "102101",
    "telephone": "0959012345",
    "email": "kriangkrai.s@example.com",
    "zipcode": "10210",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "18",
    "appointed_date": "2014-04-01",
    "retired_date": "2031-05-08",
    "status_id": "1"
  },
  {
    "ds2001_id": 19,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000019",
    "prefix_name_id": "2",
    "stf_fname": "กานดา",
    "stf_mname": "",
    "stf_lname": "บุญทวี",
    "stf_fname_en": "Kanda",
    "stf_mname_en": "",
    "stf_lname_en": "Boontawee",
    "gender_id": "2",
    "birthday": "1993-02-14",
    "homeadd": "100",
    "moo": "10",
    "street": "รัชดาภิเษก",
    "sub_district_id": "103201",
    "telephone": "0960123456",
    "email": "kanda.b@example.com",
    "zipcode": "10320",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "19",
    "appointed_date": "2023-01-01",
    "retired_date": "2053-02-14",
    "status_id": "1"
  },
  {
    "ds2001_id": 20,
    "academic_year": "2568",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000020",
    "prefix_name_id": "3",
    "stf_fname": "ชูชัย",
    "stf_mname": "",
    "stf_lname": "ยิ่งเจริญ",
    "stf_fname_en": "Chuchai",
    "stf_mname_en": "",
    "stf_lname_en": "Yingjaroen",
    "gender_id": "1",
    "birthday": "1969-11-20",
    "homeadd": "110",
    "moo": "1",
    "street": "บางนา-ตราด",
    "sub_district_id": "102601",
    "telephone": "0971234567",
    "email": "chuchai.y@example.com",
    "zipcode": "10260",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "20",
    "appointed_date": "2010-10-10",
    "retired_date": "2029-11-20",
    "status_id": "1"
  },
  {
    "ds2001_id": 21,
    "academic_year": "2568",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000021",
    "prefix_name_id": "2",
    "stf_fname": "ลลนา",
    "stf_mname": "",
    "stf_lname": "มีเงิน",
    "stf_fname_en": "Lalana",
    "stf_mname_en": "",
    "stf_lname_en": "Meengan",
    "gender_id": "2",
    "birthday": "1991-08-01",
    "homeadd": "120",
    "moo": "2",
    "street": "เจริญนคร",
    "sub_district_id": "106001",
    "telephone": "0982345678",
    "email": "lalana.m@example.com",
    "zipcode": "10600",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "21",
    "appointed_date": "2021-03-01",
    "retired_date": "2051-08-01",
    "status_id": "1"
  },
  {
    "ds2001_id": 22,
    "academic_year": "2569",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000022",
    "prefix_name_id": "3",
    "stf_fname": "วิทยา",
    "stf_mname": "",
    "stf_lname": "คงทน",
    "stf_fname_en": "Witthaya",
    "stf_mname_en": "",
    "stf_lname_en": "Kongton",
    "gender_id": "1",
    "birthday": "1974-12-05",
    "homeadd": "130",
    "moo": "3",
    "street": "พัฒนาการ",
    "sub_district_id": "102501",
    "telephone": "0993456789",
    "email": "witthaya.k@example.com",
    "zipcode": "10250",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "22",
    "appointed_date": "2016-07-01",
    "retired_date": "2034-12-05",
    "status_id": "1"
  },
  {
    "ds2001_id": 23,
    "academic_year": "2569",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000023",
    "prefix_name_id": "2",
    "stf_fname": "พิมพร",
    "stf_mname": "",
    "stf_lname": "อยู่ดี",
    "stf_fname_en": "Pimporn",
    "stf_mname_en": "",
    "stf_lname_en": "Yoodi",
    "gender_id": "2",
    "birthday": "1994-04-16",
    "homeadd": "140",
    "moo": "4",
    "street": "สีลม",
    "sub_district_id": "105001",
    "telephone": "0804567890",
    "email": "pimporn.y@example.com",
    "zipcode": "10500",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "23",
    "appointed_date": "2024-01-15",
    "retired_date": "2054-04-16",
    "status_id": "1"
  },
  {
    "ds2001_id": 24,
    "academic_year": "2570",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000024",
    "prefix_name_id": "3",
    "stf_fname": "กิติพงษ์",
    "stf_mname": "",
    "stf_lname": "รุ่งอรุณ",
    "stf_fname_en": "Kittipong",
    "stf_mname_en": "",
    "stf_lname_en": "Rungaroon",
    "gender_id": "1",
    "birthday": "1972-01-28",
    "homeadd": "150",
    "moo": "5",
    "street": "พญาไท",
    "sub_district_id": "104001",
    "telephone": "0815678901",
    "email": "kittipong.r@example.com",
    "zipcode": "10400",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "24",
    "appointed_date": "2015-09-01",
    "retired_date": "2032-01-28",
    "status_id": "1"
  },
  {
    "ds2001_id": 25,
    "academic_year": "2570",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000025",
    "prefix_name_id": "2",
    "stf_fname": "ปาริฉัตร",
    "stf_mname": "",
    "stf_lname": "สว่างสุข",
    "stf_fname_en": "Parichat",
    "stf_mname_en": "",
    "stf_lname_en": "Sawangsook",
    "gender_id": "2",
    "birthday": "1995-03-29",
    "homeadd": "160",
    "moo": "6",
    "street": "ลาดกระบัง",
    "sub_district_id": "105201",
    "telephone": "0826789012",
    "email": "parichat.s@example.com",
    "zipcode": "10520",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "25",
    "appointed_date": "2023-05-01",
    "retired_date": "2055-03-29",
    "status_id": "1"
  },
  {
    "ds2001_id": 26,
    "academic_year": "2567",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000026",
    "prefix_name_id": "3",
    "stf_fname": "ปัญญา",
    "stf_mname": "",
    "stf_lname": "เจริญยิ่ง",
    "stf_fname_en": "Panya",
    "stf_mname_en": "",
    "stf_lname_en": "Charoenyeing",
    "gender_id": "1",
    "birthday": "1965-08-08",
    "homeadd": "170",
    "moo": "7",
    "street": "ประชาอุทิศ",
    "sub_district_id": "101401",
    "telephone": "0837890123",
    "email": "panya.c@example.com",
    "zipcode": "10140",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "26",
    "appointed_date": "2008-01-01",
    "retired_date": "2025-08-08",
    "status_id": "1"
  },
  {
    "ds2001_id": 27,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000027",
    "prefix_name_id": "2",
    "stf_fname": "ดารณี",
    "stf_mname": "",
    "stf_lname": "มีบุญ",
    "stf_fname_en": "Daranee",
    "stf_mname_en": "",
    "stf_lname_en": "Meeboon",
    "gender_id": "2",
    "birthday": "1990-11-11",
    "homeadd": "180",
    "moo": "8",
    "street": "ลาดพร้าว 71",
    "sub_district_id": "102302",
    "telephone": "0848901234",
    "email": "daranee.m@example.com",
    "zipcode": "10230",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "27",
    "appointed_date": "2020-02-20",
    "retired_date": "2050-11-11",
    "status_id": "1"
  },
  {
    "ds2001_id": 28,
    "academic_year": "2568",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000028",
    "prefix_name_id": "3",
    "stf_fname": "ประสงค์",
    "stf_mname": "",
    "stf_lname": "สมบูรณ์",
    "stf_fname_en": "Prasong",
    "stf_mname_en": "",
    "stf_lname_en": "Somboon",
    "gender_id": "1",
    "birthday": "1977-06-15",
    "homeadd": "190",
    "moo": "9",
    "street": "เกษตร-นวมินทร์",
    "sub_district_id": "102303",
    "telephone": "0859012345",
    "email": "prasong.s@example.com",
    "zipcode": "10230",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "28",
    "appointed_date": "2018-04-01",
    "retired_date": "2037-06-15",
    "status_id": "1"
  },
  {
    "ds2001_id": 29,
    "academic_year": "2568",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000029",
    "prefix_name_id": "2",
    "stf_fname": "กัญญา",
    "stf_mname": "",
    "stf_lname": "ใจดี",
    "stf_fname_en": "Kanya",
    "stf_mname_en": "",
    "stf_lname_en": "Jaidee",
    "gender_id": "2",
    "birthday": "1996-09-09",
    "homeadd": "200",
    "moo": "10",
    "street": "ลาดพร้าว 101",
    "sub_district_id": "102402",
    "telephone": "0860123456",
    "email": "kanya.j@example.com",
    "zipcode": "10240",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "29",
    "appointed_date": "2024-03-10",
    "retired_date": "2056-09-09",
    "status_id": "1"
  },
  {
    "ds2001_id": 30,
    "academic_year": "2569",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000030",
    "prefix_name_id": "3",
    "stf_fname": "ทวีชัย",
    "stf_mname": "",
    "stf_lname": "มีชัย",
    "stf_fname_en": "Taweechai",
    "stf_mname_en": "",
    "stf_lname_en": "Meechai",
    "gender_id": "1",
    "birthday": "1960-02-02",
    "homeadd": "210",
    "moo": "1",
    "street": "สีลม",
    "sub_district_id": "105001",
    "telephone": "0871234567",
    "email": "taweechai.m@example.com",
    "zipcode": "10500",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "30",
    "appointed_date": "2005-01-01",
    "retired_date": "2020-02-02",
    "status_id": "1"
  },
  {
    "ds2001_id": 31,
    "academic_year": "2569",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000031",
    "prefix_name_id": "2",
    "stf_fname": "อุไรวรรณ",
    "stf_mname": "",
    "stf_lname": "สุขสบาย",
    "stf_fname_en": "Uraiwan",
    "stf_mname_en": "",
    "stf_lname_en": "Suksabai",
    "gender_id": "2",
    "birthday": "1997-05-18",
    "homeadd": "220",
    "moo": "2",
    "street": "พระราม 4",
    "sub_district_id": "101201",
    "telephone": "0882345678",
    "email": "uraiwan.s@example.com",
    "zipcode": "10120",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "31",
    "appointed_date": "2025-01-01",
    "retired_date": "2057-05-18",
    "status_id": "1"
  },
  {
    "ds2001_id": 32,
    "academic_year": "2570",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000032",
    "prefix_name_id": "3",
    "stf_fname": "อำนาจ",
    "stf_mname": "",
    "stf_lname": "สง่างาม",
    "stf_fname_en": "Amnat",
    "stf_mname_en": "",
    "stf_lname_en": "Sangangam",
    "gender_id": "1",
    "birthday": "1963-10-25",
    "homeadd": "230",
    "moo": "3",
    "street": "ประชาราษฎร์บำเพ็ญ",
    "sub_district_id": "103202",
    "telephone": "0893456789",
    "email": "amnat.s@example.com",
    "zipcode": "10320",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "32",
    "appointed_date": "2010-06-01",
    "retired_date": "2023-10-25",
    "status_id": "1"
  },
  {
    "ds2001_id": 33,
    "academic_year": "2567",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000033",
    "prefix_name_id": "2",
    "stf_fname": "วันดี",
    "stf_mname": "",
    "stf_lname": "มีชัย",
    "stf_fname_en": "Wandee",
    "stf_mname_en": "",
    "stf_lname_en": "Meechai",
    "gender_id": "2",
    "birthday": "1998-01-01",
    "homeadd": "240",
    "moo": "4",
    "street": "ลาดพร้าว 80",
    "sub_district_id": "102304",
    "telephone": "0904567890",
    "email": "wandee.m@example.com",
    "zipcode": "10230",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "33",
    "appointed_date": "2026-03-01",
    "retired_date": "2058-01-01",
    "status_id": "1"
  },
  {
    "ds2001_id": 34,
    "academic_year": "2567",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000034",
    "prefix_name_id": "3",
    "stf_fname": "บุญชัย",
    "stf_mname": "",
    "stf_lname": "สุขสันต์",
    "stf_fname_en": "Boonchai",
    "stf_mname_en": "",
    "stf_lname_en": "Suksant",
    "gender_id": "1",
    "birthday": "1967-07-07",
    "homeadd": "250",
    "moo": "5",
    "street": "สุขสวัสดิ์ 26",
    "sub_district_id": "101501",
    "telephone": "0915678901",
    "email": "boonchai.s@example.com",
    "zipcode": "10150",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "34",
    "appointed_date": "2013-08-01",
    "retired_date": "2027-07-07",
    "status_id": "1"
  },
  {
    "ds2001_id": 35,
    "academic_year": "2568",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000035",
    "prefix_name_id": "2",
    "stf_fname": "วาสนา",
    "stf_mname": "",
    "stf_lname": "โชคอำนวย",
    "stf_fname_en": "Wasana",
    "stf_mname_en": "",
    "stf_lname_en": "Chokamnuay",
    "gender_id": "2",
    "birthday": "1999-04-04",
    "homeadd": "260",
    "moo": "6",
    "street": "พระราม 2",
    "sub_district_id": "101502",
    "telephone": "0826789012",
    "email": "wasana.c@example.com",
    "zipcode": "10150",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "35",
    "appointed_date": "2027-01-01",
    "retired_date": "2059-04-04",
    "status_id": "1"
  },
  {
    "ds2001_id": 36,
    "academic_year": "2568",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000036",
    "prefix_name_id": "3",
    "stf_fname": "สุรชัย",
    "stf_mname": "",
    "stf_lname": "คงกระพัน",
    "stf_fname_en": "Surachai",
    "stf_mname_en": "",
    "stf_lname_en": "Kongkrapan",
    "gender_id": "1",
    "birthday": "1966-09-19",
    "homeadd": "270",
    "moo": "7",
    "street": "เพชรเกษม",
    "sub_district_id": "101601",
    "telephone": "0837890123",
    "email": "surachai.k@example.com",
    "zipcode": "10160",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "36",
    "appointed_date": "2012-05-01",
    "retired_date": "2026-09-19",
    "status_id": "1"
  },
  {
    "ds2001_id": 37,
    "academic_year": "2569",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000037",
    "prefix_name_id": "2",
    "stf_fname": "จินตนา",
    "stf_mname": "",
    "stf_lname": "ร่ำรวย",
    "stf_fname_en": "Jintana",
    "stf_mname_en": "",
    "stf_lname_en": "Rumruay",
    "gender_id": "2",
    "birthday": "2000-01-30",
    "homeadd": "280",
    "moo": "8",
    "street": "บางแค",
    "sub_district_id": "101602",
    "telephone": "0848901234",
    "email": "jintana.r@example.com",
    "zipcode": "10160",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "37",
    "appointed_date": "2028-02-01",
    "retired_date": "2060-01-30",
    "status_id": "1"
  },
  {
    "ds2001_id": 38,
    "academic_year": "2569",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000038",
    "prefix_name_id": "3",
    "stf_fname": "พงศ์เทพ",
    "stf_mname": "",
    "stf_lname": "มีทรัพย์",
    "stf_fname_en": "Pongthep",
    "stf_mname_en": "",
    "stf_lname_en": "Meesub",
    "gender_id": "1",
    "birthday": "1968-03-03",
    "homeadd": "290",
    "moo": "9",
    "street": "พระราม 5",
    "sub_district_id": "103001",
    "telephone": "0859012345",
    "email": "pongthep.m@example.com",
    "zipcode": "10300",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "38",
    "appointed_date": "2014-07-01",
    "retired_date": "2028-03-03",
    "status_id": "1"
  },
  {
    "ds2001_id": 39,
    "academic_year": "2570",
    "semester": "1",
    "univ_id": "2600",
    "citizen_id": "1000000000039",
    "prefix_name_id": "2",
    "stf_fname": "กมลรัตน์",
    "stf_mname": "",
    "stf_lname": "เจริญสุข",
    "stf_fname_en": "Kamolrat",
    "stf_mname_en": "",
    "stf_lname_en": "Charoensook",
    "gender_id": "2",
    "birthday": "2001-06-20",
    "homeadd": "300",
    "moo": "10",
    "street": "สาทร",
    "sub_district_id": "101202",
    "telephone": "0860123456",
    "email": "kamolrat.c@example.com",
    "zipcode": "10120",
    "nationality_id": "TH",
    "stafftype_id": "2",
    "time_contact_id": "2",
    "budget_id": "2",
    "substafftype_id": "2",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "3",
    "position_id": "212",
    "position_type_id": "2",
    "class_id": "2",
    "class_code": "2",
    "faculty_id": "66",
    "department_id": "166",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "39",
    "appointed_date": "2029-01-01",
    "retired_date": "2061-06-20",
    "status_id": "1"
  },
  {
    "ds2001_id": 40,
    "academic_year": "2570",
    "semester": "2",
    "univ_id": "2600",
    "citizen_id": "1000000000040",
    "prefix_name_id": "3",
    "stf_fname": "สมบูรณ์",
    "stf_mname": "",
    "stf_lname": "มีลาภ",
    "stf_fname_en": "Sombool",
    "stf_mname_en": "",
    "stf_lname_en": "Meelarp",
    "gender_id": "1",
    "birthday": "1962-11-11",
    "homeadd": "310",
    "moo": "1",
    "street": "เจริญกรุง",
    "sub_district_id": "101001",
    "telephone": "0871234567",
    "email": "sombool.m@example.com",
    "zipcode": "10100",
    "nationality_id": "TH",
    "stafftype_id": "1",
    "time_contact_id": "1",
    "budget_id": "1",
    "substafftype_id": "1",
    "admin_position_id": "0",
    "academicstanding_id": "-",
    "positionlevel_id": "4",
    "position_id": "211",
    "position_type_id": "1",
    "class_id": "1",
    "class_code": "1",
    "faculty_id": "65",
    "department_id": "165",
    "division_id": "0",
    "section_id": "0",
    "work_status_id": "1",
    "tax_status_id": "1",
    "salary": "0",
    "pos_no": "40",
    "appointed_date": "2009-03-01",
    "retired_date": "2022-11-11",
    "status_id": "1"
  }
];
// *** สิ้นสุดข้อมูลประมาณ 40 รายการ ***


// --- คอมโพเนนต์ StaffTable (รวมอยู่ในไฟล์เดียวกัน) ---
interface StaffTableProps {
  data: StaffData[];
}

const StaffTable: React.FC<StaffTableProps> = ({ data }) => {
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const { messages } = useIntl();

  const handleChangePage = (event: unknown, newPage: number) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRowsPerPage(+event.target.value);
    setPage(0);
  };

  if (data.length === 0) {
    return (
      <Typography variant="h6" color="textSecondary" align="center" sx={{ mt: 4 }}>
        <IntlMessages id="common_no_data" defaultMessage="ไม่มีข้อมูลที่ตรงกับเงื่อนไข"/>
      </Typography>
    );
  }

  return (
    <Paper sx={{ width: '100%', overflow: 'hidden' }}>
      <TableContainer sx={{ maxHeight: 600 }}>
        <Table stickyHeader aria-label="staff table">
          <TableHead>
            <TableRow>
              <TableCell>รหัสบุคลากร</TableCell>
              <TableCell>ปีการศึกษา</TableCell>
              <TableCell>ชื่อ (ไทย)</TableCell>
              <TableCell>นามสกุล (ไทย)</TableCell>
              <TableCell>ชื่อ (EN)</TableCell>
              <TableCell>นามสกุล (EN)</TableCell>
              <TableCell>เบอร์โทรศัพท์</TableCell>
              <TableCell>อีเมล</TableCell>
              <TableCell>สถานะการทำงาน</TableCell>
              {/* เพิ่มคอลัมน์อื่นๆ ตามต้องการ */}
            </TableRow>
          </TableHead>
          <TableBody>
            {data
              .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
              .map((row) => (
                <TableRow hover role="checkbox" tabIndex={-1} key={row.ds2001_id}>
                  <TableCell>{row.ds2001_id}</TableCell>
                  <TableCell>{row.academic_year}</TableCell>
                  <TableCell>{row.stf_fname}</TableCell>
                  <TableCell>{row.stf_lname}</TableCell>
                  <TableCell>{row.stf_fname_en}</TableCell>
                  <TableCell>{row.stf_lname_en}</TableCell>
                  <TableCell>{row.telephone === '-' ? '' : row.telephone}</TableCell>
                  <TableCell>{row.email === '-' ? '' : row.email}</TableCell>
                  <TableCell>{row.work_status_id}</TableCell>
                  {/* เพิ่ม Cell ของข้อมูลอื่นๆ */}
                </TableRow>
              ))}
          </TableBody>
        </Table>
      </TableContainer>
      <TablePagination
        rowsPerPageOptions={[10, 25, 50, 100]}
        component="div"
        count={data.length}
        rowsPerPage={rowsPerPage}
        page={page}
        onPageChange={handleChangePage}
        onRowsPerPageChange={handleChangeRowsPerPage}
        labelRowsPerPage={<IntlMessages id="table_rows_per_page" defaultMessage="จำนวนแถวต่อหน้า:"/>}
        labelDisplayedRows={({ from, to, count }) =>
          `${from}-${to} จาก ${count !== -1 ? count : `มากกว่า ${to}`}`
        }
      />
    </Paper>
  );
};


// --- ฟังก์ชันสำหรับส่งออก Excel (รวมอยู่ในไฟล์เดียวกัน) ---
const exportToExcel = (data: any[], fileName: string, sheetName: string) => {
  if (data.length === 0) {
    Swal.fire('ไม่มีข้อมูล', 'ไม่สามารถส่งออกไฟล์ Excel ได้เนื่องจากไม่มีข้อมูล', 'info');
    return;
  }

  const dataForExport = data.map(item => ({
    'รหัสบุคลากร': item.ds2001_id,
    'ปีการศึกษา': item.academic_year,
    'ภาคเรียน': item.semester,
    'รหัสหน่วยงาน': item.univ_id,
    'เลขบัตรประชาชน': item.citizen_id,
    'คำนำหน้า (ไทย)': item.prefix_name_id,
    'ชื่อ (ไทย)': item.stf_fname,
    'นามสกุล (ไทย)': item.stf_lname,
    'ชื่อ (EN)': item.stf_fname_en,
    'นามสกุล (EN)': item.stf_lname_en,
    'เพศ': item.gender_id,
    'วันเกิด': item.birthday,
    'ที่อยู่': item.homeadd,
    'หมู่': item.moo,
    'ถนน': item.street,
    'ตำบล/แขวง ID': item.sub_district_id,
    'เบอร์โทรศัพท์': item.telephone,
    'อีเมล': item.email,
    'รหัสไปรษณีย์': item.zipcode,
    'สัญชาติ ID': item.nationality_id,
    'ประเภทบุคลากร ID': item.stafftype_id,
    'เวลาติดต่อ ID': item.time_contact_id,
    'งบประมาณ ID': item.budget_id,
    'ประเภทย่อยบุคลากร ID': item.substafftype_id,
    'ตำแหน่งบริหาร ID': item.admin_position_id,
    'วิทยฐานะ ID': item.academicstanding_id,
    'ระดับตำแหน่ง ID': item.positionlevel_id,
    'ตำแหน่ง ID': item.position_id,
    'ประเภทตำแหน่ง ID': item.position_type_id,
    'รหัสประเภท': item.class_id,
    'รหัสประเภท (Code)': item.class_code,
    'รหัสคณะ': item.faculty_id,
    'รหัสภาควิชา': item.department_id,
    'รหัสฝ่าย': item.division_id,
    'รหัสส่วนงาน': item.section_id,
    'สถานะการทำงาน ID': item.work_status_id,
    'สถานะภาษี ID': item.tax_status_id,
    'เงินเดือน': item.salary,
    'เลขที่ตำแหน่ง': item.pos_no,
    'วันที่เริ่มงาน': item.appointed_date,
    'วันที่เกษียณ': item.retired_date,
    'สถานะ ID': item.status_id,
  }));


  const ws = XLSX.utils.json_to_sheet(dataForExport);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  saveAs(new Blob([excelBuffer], { type: 'application/octet-stream' }), fileName + '.xlsx');

  Swal.fire('สำเร็จ!', 'ส่งออกข้อมูลเป็น Excel เรียบร้อยแล้ว', 'success');
};

// --- ฟังก์ชันสำหรับส่งออก PDF (หากต้องการใช้) ---
const exportToPdf = (data: StaffData[], fileName: string, title: string) => {
  if (data.length === 0) {
    Swal.fire('ไม่มีข้อมูล', 'ไม่สามารถส่งออกไฟล์ PDF ได้เนื่องจากไม่มีข้อมูล', 'info');
    return;
  }

  const doc = new jsPDF(); // หากไม่ใช้ font ไทยพิเศษ

  const tableColumn = [
    "รหัส",
    "ปี",
    "ชื่อ (ไทย)",
    "นามสกุล (ไทย)",
    "ชื่อ (EN)",
    "นามสกุล (EN)",
    "โทรศัพท์",
    "อีเมล",
    "สถานะ"
  ];
  const tableRows = data.map(item => [
    item.ds2001_id,
    item.academic_year,
    item.stf_fname,
    item.stf_lname,
    item.stf_fname_en,
    item.stf_lname_en,
    item.telephone === '-' ? '' : item.telephone,
    item.email === '-' ? '' : item.email,
    item.work_status_id
  ]);

  (doc as any).autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    // styles: { fontSize: 8, font: 'NotoSansThai' }, // ใช้ 'NotoSansThai' หากตั้งค่า Font ไว้สำหรับ jsPDF
    headStyles: { fillColor: [15, 103, 203] },
    margin: { top: 20 },
  });

  doc.setFontSize(18);
  doc.text(title, 14, 40);

  doc.save(`${fileName}.pdf`);
  Swal.fire('สำเร็จ!', 'ส่งออกข้อมูลเป็น PDF เรียบร้อยแล้ว', 'success');
};


// --- คอมโพเนนต์หลักของหน้า (คล้ายกับ App.tsx เดิม) ---
const StaffPage: React.FC = () => {
  const { messages } = useIntl();
  const [selectedYear, setSelectedYear] = useState<string>('');
  const [filteredData, setFilteredData] = useState<StaffData[]>([]);
  // ดึงปีการศึกษาที่ไม่ซ้ำกันจาก allStaffData
  const academicYears = Array.from(new Set(allStaffData.map(item => item.academic_year))).sort();


  // ตั้งค่าข้อมูลเริ่มต้นเมื่อคอมโพเนนต์โหลดครั้งแรก
  useEffect(() => {
    setFilteredData(allStaffData);
  }, []);

  const handleGenerateReport = useCallback(() => {
    if (selectedYear) {
      const filtered = allStaffData.filter(
        (item) => item.academic_year === selectedYear
      );
      setFilteredData(filtered);
    } else {
      setFilteredData(allStaffData); // ถ้าไม่ได้เลือกปี ให้แสดงข้อมูลทั้งหมด
    }
    Swal.fire('สร้างรายงาน', 'รายงานข้อมูลบุคลากรถูกสร้างแล้ว', 'success');
  }, [selectedYear]);

  const handleExportExcel = useCallback(() => {
    exportToExcel(filteredData, `staff_report_${selectedYear || 'all'}`, 'Staff Data');
  }, [filteredData, selectedYear]);

  const handleExportPdf = useCallback(() => {
    exportToPdf(filteredData, `staff_report_${selectedYear || 'all'}`, 'รายงานข้อมูลบุคลากร');
  }, [filteredData, selectedYear]);


  return (
    <AppsContent>
      <AppInfoView />
      <AppCard title={<IntlMessages id="staff_management_title" defaultMessage="ข้อมูลพื้นฐานบุคลากร (UOC Staff)"/>}>
        <Box sx={{ display: 'flex', gap: 2, mb: 3, alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <FormControl sx={{ minWidth: 120 }}>
            <InputLabel id="academic-year-select-label">ปีการศึกษา</InputLabel>
            <Select
              labelId="academic-year-select-label"
              id="academic-year-select"
              value={selectedYear}
              label="ปีการศึกษา"
              onChange={(e) => setSelectedYear(e.target.value as string)}
            >
              <MenuItem value="">
                <em><IntlMessages id="year_all" defaultMessage="ทั้งหมด"/></em>
              </MenuItem>
              {academicYears.map((year) => (
                <MenuItem key={year} value={year}>
                  {year}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <Button variant="contained" onClick={handleGenerateReport}>
            <IntlMessages id="generate_report_button" defaultMessage="สร้างรายงาน"/>
          </Button>
          <Button variant="outlined" onClick={handleExportExcel}>
            <IntlMessages id="export_excel_button" defaultMessage="ส่งออกข้อมูลเป็น Excel"/>
          </Button>
          <Button variant="outlined" onClick={handleExportPdf}>
            <IntlMessages id="export_pdf_button" defaultMessage="ส่งออกข้อมูลเป็น PDF"/>
          </Button>
        </Box>
        <StaffTable data={filteredData} />
      </AppCard>
    </AppsContent>
  );
};

export default StaffPage;

// --- Root rendering ของ React ---
// ส่วนนี้มีไว้สำหรับการทดสอบ หากคุณใช้เฟรมเวิร์กอย่าง Next.js หรือ Vite
// และมีไฟล์ index.tsx/main.tsx อยู่แล้ว โปรดลบโค้ดนี้ออก
// และเรียกใช้ <StaffPage /> ในไฟล์หลักของโปรเจกต์คุณแทน
if (typeof window !== 'undefined') {
  const rootElement = document.getElementById('root');
  if (rootElement) {
    const root = ReactDOM.createRoot(rootElement);
    root.render(
      <React.StrictMode>
        <StaffPage />
      </React.StrictMode>
    );
  }
}
