import { useState, useEffect, useMemo, useCallback } from 'react';
import { Staff } from '../interfaces/StaffSource.interface';
import { UOCStaff } from '../interfaces/UOCStaff.interface';
import { MappedStaff } from '../interfaces/MappedStaff.interface';

// ข้อมูลจำลอง (Mock Data) สำหรับ Source Staff
const mockSourceStaffs: Staff[] = [
  {
    staff_id: 'S001', citizen_id: '1111111111111', prefixname_id: 1, first_name_th: 'สมชาย', last_name_th: 'จริงใจ', email1: 'somchai@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S002', citizen_id: '2222222222222', prefixname_id: 2, first_name_th: 'สมหญิง', last_name_th: 'มั่งคั่ง', email1: 'somying@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S003', citizen_id: '3333333333333', prefixname_id: 3, first_name_th: 'มานะ', last_name_th: 'อดทน', email1: 'mana@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S004', citizen_id: '4444444444444', prefixname_id: 1, first_name_th: 'วีระ', last_name_th: 'กล้าหาญ', email1: 'veera@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S005', citizen_id: '5555555555555', prefixname_id: 2, first_name_th: 'ดารณี', last_name_th: 'สุขสันต์', email1: 'daranee@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S006', citizen_id: '6666666666666', prefixname_id: 1, first_name_th: 'เอกชัย', last_name_th: 'เมตตา', email1: 'ekachai@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
  {
    staff_id: 'S007', citizen_id: '7777777777777', prefixname_id: 2, first_name_th: 'อารีย์', last_name_th: 'ใจดี', email1: 'aree@example.com',
    foreigner_id: null,
    academic_title: null,
    middle_name_th: null,
    first_name_en: null,
    last_name_en: null,
    middle_name_en: null,
    gender: null,
    ethnicity: null,
    nationality: null,
    religion: null,
    date_of_birth: null,
    birth_province: null,
    current_address: null,
    house_registration_address: null,
    domicile_address: null,
    country: null,
    marital_status: null,
    military_status: null,
    enlistment_date: null,
    ordained_temple: null,
    ordained_date: null,
    blood_type: null,
    weight: null,
    height: null,
    phone_number: null,
    mobile_number1: null,
    mobile_number2: null,
    email2: null,
    line_id: null,
    budget_type: null,
    profile_picture: null,
    hobbies: null,
    language_skills: null,
    computer_skills: null,
    create_at: null,
    update_at: null,
    officer_id: null,
    faculty_id: null,
    department_id: null,
    program_id: null,
    staff_status: null,
    staff_type_id: null,
    position_type_id: null,
    job_title_id: null,
    work_line_id: null,
    position_level_id: null,
    academic_position_id: null,
    support_position_id: null,
    admin_position_id: null
  },
];

// ข้อมูลจำลอง (Mock Data) สำหรับ UOC Staff
const mockUOCStaffs: UOCStaff[] = [
  {
    ds2001_id: 'U001', citizen_id: '1111111111111', prefix_name_id: '1', stf_fname: 'สมชาย', stf_lname: 'จริงใจ', email: 'somchai_uoc@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U002', citizen_id: '2222222222222', prefix_name_id: '2', stf_fname: 'สมหญิง', stf_lname: 'มั่งคั่ง', email: 'somying_uoc@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U003', citizen_id: '8888888888888', prefix_name_id: '1', stf_fname: 'ธนา', stf_lname: 'ร่ำรวย', email: 'thana@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U004', citizen_id: '9999999999999', prefix_name_id: '2', stf_fname: 'อรุณี', stf_lname: 'ผ่องใส', email: 'arunee@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U005', citizen_id: '5555555555555', prefix_name_id: '2', stf_fname: 'ดารณี', stf_lname: 'สุขสันต์', email: 'daranee_uoc@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U006', citizen_id: '6666666666666', prefix_name_id: '1', stf_fname: 'เอกชัย', stf_lname: 'เมตตา', email: 'ekachai_uoc@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
  {
    ds2001_id: 'U007', citizen_id: '7777777777777', prefix_name_id: '2', stf_fname: 'อารีย์', stf_lname: 'ใจดี', email: 'aree_uoc@example.com',
    academic_year: null,
    semester: null,
    univ_id: null,
    stf_mname: null,
    stf_fname_en: null,
    stf_mname_en: null,
    stf_lname_en: null,
    gender_id: null,
    birthday: null,
    homeadd: null,
    moo: null,
    street: null,
    sub_district_id: null,
    telephone: null,
    zipcode: null,
    nationality_id: null,
    stafftype_id: null,
    time_contact_id: null,
    budget_id: null,
    substafftype_id: null,
    admin_position_id: null,
    academicstanding_id: null,
    positionlevel_id: null,
    position_work: null,
    department_id: null,
    date_inwork: null,
    date_start_this_u: null,
    special_name_id_1: null,
    special_name_id_2: null,
    teach_level_id: null,
    deform_id: null,
    income_id: null,
    movement_type_id: null,
    movement_date: null,
    decoration_id: null,
    decoration_date: null,
    passport_startdate: null,
    passport_enddate: null,
    appointment_order: null,
    appointment_order_start_date: null,
    appointment_dismissal: null,
    appointment_dismissal_date: null,
    scholar_order_id: null,
    scholar_order_date: null,
    academicstanding_subject_id: null,
    academicstanding_subject_other: null,
    researcher_status_id: null
  },
];

const useStaffMapping = () => {
  const [sourceStaffs, setSourceStaffs] = useState<Staff[]>(mockSourceStaffs);
  const [uocStaffs, setUocStaffs] = useState<UOCStaff[]>(mockUOCStaffs);
  const [mappedStaffs, setMappedStaffs] = useState<MappedStaff[]>([]);

  const [selectedSourceStaffs, setSelectedSourceStaffs] = useState<Staff[]>([]); // เปลี่ยนเป็น Array
  const [selectedUOCStaffs, setSelectedUOCStaffs] = useState<UOCStaff[]>([]);   // เปลี่ยนเป็น Array

  const [sourceSearchTerm, setSourceSearchTerm] = useState<string>('');
  const [uocSearchTerm, setUocSearchTerm] = useState<string>('');

  // ฟังก์ชันสำหรับการเพิ่ม/ลบ Staff จากรายการที่เลือก
  const handleToggleSourceStaff = useCallback((staff: Staff) => {
    setSelectedSourceStaffs((prevSelected) =>
      prevSelected.some((s) => s.staff_id === staff.staff_id)
        ? prevSelected.filter((s) => s.staff_id !== staff.staff_id)
        : [...prevSelected, staff]
    );
  }, []);

  // ฟังก์ชันสำหรับการเพิ่ม/ลบ UOC Staff จากรายการที่เลือก
  const handleToggleUOCStaff = useCallback((uocStaff: UOCStaff) => {
    setSelectedUOCStaffs((prevSelected) =>
      prevSelected.some((s) => s.ds2001_id === uocStaff.ds2001_id)
        ? prevSelected.filter((s) => s.ds2001_id !== uocStaff.ds2001_id)
        : [...prevSelected, uocStaff]
    );
  }, []);

  const filteredSourceStaffs = useMemo(() => {
    return sourceStaffs.filter((staff) =>
      staff.first_name_th.toLowerCase().includes(sourceSearchTerm.toLowerCase()) ||
      staff.last_name_th.toLowerCase().includes(sourceSearchTerm.toLowerCase()) ||
      staff.citizen_id.includes(sourceSearchTerm) ||
      staff.staff_id.includes(sourceSearchTerm)
    );
  }, [sourceStaffs, sourceSearchTerm]);

  const filteredUOCStaffs = useMemo(() => {
    return uocStaffs.filter((uocStaff) =>
      uocStaff.stf_fname.toLowerCase().includes(uocSearchTerm.toLowerCase()) ||
      uocStaff.stf_lname.toLowerCase().includes(uocSearchTerm.toLowerCase()) ||
      uocStaff.citizen_id.includes(uocSearchTerm) ||
      uocStaff.ds2001_id.includes(uocSearchTerm)
    );
  }, [uocStaffs, uocSearchTerm]);

  // handleSaveMapping จะต้องวนลูปบันทึกทุกคู่ที่เลือก
  const handleSaveMapping = useCallback(() => {
    const newMappings: MappedStaff[] = [];
    // สำหรับแต่ละคู่ที่ถูกเลือก (เราจะสมมติว่าผู้ใช้เลือก Staff และ UOC Staff เป็นคู่ๆ)
    // ใน UI เราจะแสดงรายการที่เลือกใน preview table
    // ที่นี่เราจะทำการวนลูปตามจำนวนคู่ที่แสดงใน preview table
    // สำหรับ MVP นี้ เราจะบันทึกเฉพาะคู่ที่ถูกแสดงใน MappingPreviewTable เท่านั้น
    // หากต้องการการจับคู่ 1-to-N หรือ N-to-N ต้องมี logic ที่ซับซ้อนกว่านี้
    // ณ ที่นี้ เราจะสร้าง mapping จาก selectedSourceStaffs และ selectedUOCStaffs แบบ 1 ต่อ 1
    // โดยสมมติว่ามีการจับคู่ตามลำดับการเลือก หรือตาม citizen_id ถ้ามี
    // **ข้อควรระวัง**: logic นี้เหมาะกับการเลือกแบบ 1:1 หรือแบบที่จับคู่กันชัดเจน
    // ถ้าต้องการจับคู่ N:N หรือ 1:N ต้องมี UI และ Logic การจับคู่ที่ซับซ้อนกว่านี้
    // สำหรับตอนนี้ เราจะสร้าง mapping จากรายการที่เลือกทั้งหมด โดยอาจจะจับคู่กันเอง หรือให้ผู้ใช้กำหนด
    // แต่เพื่อความง่ายในตอนนี้ จะถือว่าแต่ละรายการใน selectedSourceStaffs
    // จะจับคู่กับรายการใน selectedUOCStaffs ตามลำดับ (ซึ่งอาจจะไม่ใช่กรณีจริงเสมอไป)
    // **ทางที่ดีกว่าคือ** ใน `MappingPreviewTable` ควรจะสร้าง "คู่" ที่จะบันทึก
    // และส่ง "คู่เหล่านั้น" มาให้ `handleSaveMapping`
    // แต่เพื่อให้สอดคล้องกับโครงสร้างเดิม เราจะถือว่า `selectedSourceStaffs` และ `selectedUOCStaffs`
    // มีรายการที่สัมพันธ์กัน หรือสร้างการจับคู่แบบง่ายๆ

    if (selectedSourceStaffs.length === 0 || selectedUOCStaffs.length === 0) {
      // ไม่ควรเกิดขึ้นถ้า UI บังคับให้เลือกทั้งคู่ก่อนกดบันทึก
      console.warn("No items selected for mapping.");
      return;
    }

    // สร้างการจับคู่จากรายการที่ถูกเลือก
    // ณ จุดนี้ เราจะสร้างคู่ใหม่สำหรับทุกๆ การจับคู่ที่ถูกแสดงใน preview table
    // สำหรับตอนนี้จะสร้างคู่จากข้อมูลที่มีอยู่แบบเรียบง่าย
    selectedSourceStaffs.forEach(sourceStaff => {
        selectedUOCStaffs.forEach(uocStaff => {
             // เช็คว่ายังไม่เคยจับคู่กัน
            const isAlreadyMapped = mappedStaffs.some(
                (m) => m.sourceStaff.staff_id === sourceStaff.staff_id && m.uocStaff.ds2001_id === uocStaff.ds2001_id
            );
            if (!isAlreadyMapped) {
                newMappings.push({
                  id: `map-${Date.now()}-${Math.random()}`, // สร้าง ID ชั่วคราว
                  sourceStaff: sourceStaff,
                  uocStaff: uocStaff,
                  mappedDate: new Date().toLocaleDateString('th-TH'),
                  mappedBy: ''
                });
            }
        });
    });

    setMappedStaffs((prevMappings) => [...prevMappings, ...newMappings]);
    setSelectedSourceStaffs([]); // ล้างรายการที่เลือกหลังจากบันทึก
    setSelectedUOCStaffs([]);
  }, [selectedSourceStaffs, selectedUOCStaffs, mappedStaffs]);


  const handleClearSelections = useCallback(() => {
    setSelectedSourceStaffs([]);
    setSelectedUOCStaffs([]);
  }, []);

  return {
    sourceStaffs,
    uocStaffs,
    mappedStaffs,
    filteredSourceStaffs,
    filteredUOCStaffs,
    selectedSourceStaffs, // ส่งคืน Array
    selectedUOCStaffs,   // ส่งคืน Array
    sourceSearchTerm,
    uocSearchTerm,
    handleToggleSourceStaff, // เปลี่ยนชื่อฟังก์ชัน
    handleToggleUOCStaff,   // เปลี่ยนชื่อฟังก์ชัน
    setSourceSearchTerm,
    setUocSearchTerm,
    handleSaveMapping,
    handleClearSelections,
  };
};

export default useStaffMapping;