import { FaRegCalendarAlt, FaRegHospital } from 'react-icons/fa';
import { FiMap, FiUsers } from 'react-icons/fi';
import { HiOutlineAcademicCap, HiOutlineChartSquareBar } from 'react-icons/hi';
import {
  RiCustomerService2Line,
  RiDashboardLine,
  RiFileUploadLine,
  RiShieldUserLine,
  RiTodoLine,
} from 'react-icons/ri';
import { BiCarousel, BiCartAlt, BiErrorAlt, BiTask } from 'react-icons/bi';
import { BsBriefcase, BsCart4, BsChatDots, BsCurrencyBitcoin, BsQuestionDiamond } from 'react-icons/bs';
import { DiHtml5Multimedia } from 'react-icons/di';
import {
  MdOutlineAnalytics,
  MdOutlineContactPhone,
  MdOutlineContactSupport,
  MdOutlineDns,
  MdOutlineManageAccounts,
  MdOutlineSettings,
  MdOutlineAppSettingsAlt,
  MdOutlineSettingsSuggest,
  MdOutlineTableChart,
  MdOutlineTableRows,
  MdOutlineDocumentScanner,
  MdOutlineFeed,
  MdOutlineFactCheck,
  MdOutlineFeaturedPlayList,
  MdOutlineFileOpen,
  MdHotelClass,
  MdLocalPlay,
  MdNordicWalking,
  MdOutlineAttribution,
  MdMan,
  MdOutlineSettingsAccessibility,
  MdOutlineSupervisorAccount,
  MdOutlineSwitchAccessShortcutAdd,
  MdOutlineTransferWithinAStation,
  MdEditDocument,
  MdContacts,
  MdContactEmergency,
} from 'react-icons/md';
import { CgFeed } from 'react-icons/cg';
import { GrUserAdmin } from 'react-icons/gr';
import { AiOutlineEdit, AiOutlineUnorderedList } from 'react-icons/ai';
import { TbFileInvoice } from 'react-icons/tb';

const routesConfig = [
  {
    id: 'hr',
    title: 'ระบบบริหารงานบุคลากร',
    messageId: 'sidebar.hr',
    icon: <MdOutlineContactPhone />,
    type: 'group',
    children: [
      {

         
          id: 'hr01',
          title: 'sidebar.hr01',
          messageId: 'sidebar.hr01',
          type: 'collapse',
          icon: <MdOutlineSettings />,
          children: [
            {
              id: 'hr101',
              title: 'sidebar.hr01.01',
              messageId: 'sidebar.hr01.01',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr101',
            },
            {
              id: 'hr102',
              title: 'sidebar.hr01.02',
              messageId: 'sidebar.hr01.02',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr102',
            },
            {
              id: 'hr103',
              title: 'sidebar.hr01.03',
              messageId: 'sidebar.hr01.03',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr103',
            },
            {
              id: 'hr104',
              title: 'sidebar.hr01.04',
              messageId: 'sidebar.hr01.04',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr104',
            },
            {
              id: 'hr105',
              title: 'sidebar.hr01.05',
              messageId: 'sidebar.hr01.05',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr105',
            },
            {
              id: 'hr106',
              title: 'sidebar.hr01.06',
              messageId: 'sidebar.hr01.06',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr106',
            },
            {
              id: 'hr107',
              title: 'sidebar.hr01.07',
              messageId: 'sidebar.hr01.07',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr107',
            },
            {
              id: 'hr108',
              title: 'sidebar.hr01.08',
              messageId: 'sidebar.hr01.08',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr108',
            },
                        {
              id: 'hr109',
              title: 'sidebar.hr01.09',
              messageId: 'sidebar.hr01.09',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr109',
            },
                       {
              id: 'hr110',
              title: 'sidebar.hr01.10',
              messageId: 'sidebar.hr01.10',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr110',
            },
                       {
              id: 'hr111',
              title: 'sidebar.hr01.11',
              messageId: 'sidebar.hr01.11',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr111',
            },
                       {
              id: 'hr115',
              title: 'sidebar.hr01.15',
              messageId: 'sidebar.hr01.15',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr115',
            },
                       {
              id: 'hr116',
              title: 'sidebar.hr01.16',
              messageId: 'sidebar.hr01.16',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr116',
            },
                          {
              id: 'hr117',
              title: 'sidebar.hr01.17',
              messageId: 'sidebar.hr01.17',
              type: 'item',
              //icon: <MdOutlineSettingsSuggest />,
              url: '/hr01/hr117',
            },


          ],
        },

         ],
  },
  { 
    id: 'hr00',
    title: 'sidebar.hr00',
    messageId: 'sidebar.hr00',
    icon: <MdOutlineContactPhone />,
    type: 'group',
    children: [
      
      {
        id: 'hr02',
        title: 'sidebar.hr02',
        messageId: 'sidebar.hr02',
        type: 'collapse',
        icon: <MdContacts />,
        children: [
          {
            id: 'hr201',
            title: 'sidebar.hr02.01',
            messageId: 'sidebar.hr02.01',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr201',
          },
          {
            id: 'hr202',
            title: 'sidebar.hr02.02',
            messageId: 'sidebar.hr02.02',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr202',
          },
          {
            id: 'hr203',
            title: 'sidebar.hr02.03',
            messageId: 'sidebar.hr02.03',
            //icon: <MdContactEmergency/>,
            type: 'item',
            url: '/hr02/hr203',
          },
          {
            id: 'hr204',
            title: 'sidebar.hr02.04',
            messageId: 'sidebar.hr02.04',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr204',
          },
          {
            id: 'hr205',
            title: 'sidebar.hr02.05',
            messageId: 'sidebar.hr02.05',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr205',
          },
          {
            id: 'hr206',
            title: 'sidebar.hr02.06',
            messageId: 'sidebar.hr02.06',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr206',
          },
          {
            id: 'hr207',
            title: 'sidebar.hr02.07',
            messageId: 'sidebar.hr02.07',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr207',
          },
          {
            id: 'hr208',
            title: 'sidebar.hr02.08',
            messageId: 'sidebar.hr02.08',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr208',
          },
          {
            id: 'hr209',
            title: 'sidebar.hr02.09',
            messageId: 'sidebar.hr02.09',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr209',
          },
          {
            id: 'hr210',
            title: 'sidebar.hr02.10',
            messageId: 'sidebar.hr02.10',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr210',
          },
          {
            id: 'hr211',
            title: 'sidebar.hr02.11',
            messageId: 'sidebar.hr02.11',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr211',
          },
          {
            id: 'hr212',
            title: 'sidebar.hr02.12',
            messageId: 'sidebar.hr02.12',
            type: 'item',
            //icon: <MdContactEmergency/>,
            url: '/hr02/hr212',
          },
        ],
      },
      {
        id: 'hr03',
        title: 'sidebar.hr03',
        messageId: 'sidebar.hr03',
        type: 'collapse',
        icon: <MdOutlineTransferWithinAStation />
      },
      {
        id: 'hr04',
        title: 'sidebar.hr04',
        messageId: 'sidebar.hr04',
        type: 'collapse',
        icon: <MdEditDocument />
      },
      {
        id: 'hr05',
        title: 'Ecommerce',
        messageId: 'sidebar.hr05',
        type: 'collapse',
        icon: <MdOutlineSwitchAccessShortcutAdd />
      },
      {
        id: 'hr06',
        title: 'sidebar.hr06',
        messageId: 'sidebar.hr06',
        type: 'collapse',
        icon: <MdOutlineSupervisorAccount />,
        children: [
          {
            id: 'hr601',
            title: 'sidebar.hr06',
            messageId: 'sidebar.hr06.01',
            type: 'item',
            //icon: <MdOutlineSupervisorAccount />,
            url: '/hr06/601',
          },
          {
            id: 'hr602',
            title: 'sidebar.hr06',
            messageId: 'sidebar.hr06.02',
            type: 'item',
            //icon: <MdOutlineSupervisorAccount />,
            url: '/hr06/602',
          },
          {
            id: 'hr603',
            title: 'sidebar.hr06',
            messageId: 'sidebar.hr06.03',
            type: 'item',
            //icon: <MdOutlineSupervisorAccount />,
            url: '/hr06/603',
          },
        ],
      },
      {
        id: 'hr07',
        title: 'sidebar.hr07',
        messageId: 'sidebar.hr07',
        type: 'collapse',
        icon: <MdOutlineSettingsAccessibility />,
        children: [
          {
            id: 'hr701',
            title: 'sidebar.hr07',
            messageId: 'sidebar.hr07.01',
            type: 'item',
            //icon: <MdOutlineSettingsAccessibility />,
            url: '/hr07/hr701',
          },
          {
            id: 'hr702',
            title: 'sidebar.hr07',
            messageId: 'sidebar.hr07.02',
            type: 'item',
            //icon: <MdOutlineSettingsAccessibility />,
            url: '/hr07/hr702',
          },
        ],
      },
      {
        id: 'hr08',
        title: 'sidebar.hr08',
        messageId: 'sidebar.hr08',
        type: 'collapse',
        icon: <MdOutlineAttribution />,
        children: [
          {
            id: 'hr801',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.01',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr801',
          },
          {
            id: 'hr802',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.02',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr802',
          },
                    {
            id: 'hr803',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.03',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr803',
          },
                    {
            id: 'hr804',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.04',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr804',
          },
                    {
            id: 'hr805',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.05',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr805',
          },
                    {
            id: 'hr806',
            title: 'sidebar.hr08',
            messageId: 'sidebar.hr08.06',
            type: 'item',
            //icon:<MdMan />,
            url: '/hr08/hr806',
          },
        ],
      },
      {
        id: 'hr09',
        title: 'sidebar.hr09',
        messageId: 'sidebar.hr09',
        type: 'collapse',
        icon: <MdHotelClass />,
        children: [
          {
            id: 'hr901',
            title: 'sidebar.hr09',
            messageId: 'sidebar.hr09.01',
            type: 'item',
            //icon: <MdLocalPlay />,
            url: '/hr09/hr901',
          },
          {
            id: 'hr902',
            title: 'sidebar.hr09',
            messageId: 'sidebar.hr09.02',
            type: 'item',
            //icon: <MdLocalPlay />,
            url: '/hr09/hr902',
          },
          {
            id: 'hr903',
            title: 'sidebar.hr09',
            messageId: 'sidebar.hr09.03',
            type: 'item',
            //icon: <MdLocalPlay />,
            url: '/hr09/hr903',
          },
        ],
      },
 

    ],
  },

  {
    id: 'rp',
    title: 'sidebar.rp',
    messageId: 'sidebar.rp',
    type: 'group',
    icon: <MdOutlineTableChart />,
    children: [
      {
        id: 'hr10',
        title: 'sidebar.hr10',
        messageId: 'sidebar.hr10',
        type: 'collapse',
        icon: <MdOutlineTableChart />,
        children: [
          {
            id: 'hr1001',
            title: 'sidebar.hr10',
            messageId: 'sidebar.hr10.01',
            type: 'item',
            //icon: <MdOutlineTableRows />,
            url: '/hr10/hr1001',
          },
          {
            id: 'hr1002',
            title: 'sidebar.hr10',
            messageId: 'sidebar.hr10.02',
            type: 'item',
            //icon: <MdOutlineTableRows />,
            url: '/hr10/hr1002',
          },
        ],
      },

      {
        id: 'rp01',
        title: 'sidebar.rp01',
        messageId: 'sidebar.rp01',
        type: 'collapse',
        icon: <MdOutlineDocumentScanner />,
        children: [
          {
            id: 'rp101',
            title: 'sidebar.rp01',
            messageId: 'sidebar.rp01.01',
            type: 'item',
            //icon:<MdOutlineFeed />,
            url: '/rp01/rp101',
          },
          {
            id: 'rp102',
            title: 'sidebar.rp01',
            messageId: 'sidebar.rp01.02',
            type: 'item',
            //icon:<MdOutlineFeed />,
            url: '/rp01/rp102',
          },
          {
            id: 'rp103',
            title: 'sidebar.rp01',
            messageId: 'sidebar.rp01.03',
            type: 'item',
            //icon:<MdOutlineFeed />,
            url: '/rp01/rp103',
          },
          {
            id: 'rp104',
            title: 'sidebar.rp01',
            messageId: 'sidebar.rp01.04',
            type: 'item',
            //icon:<MdOutlineFeed />,
            url: '/rp01/rp104',
          },
          {
            id: 'rp105',
            title: 'sidebar.rp01',
            messageId: 'sidebar.rp01.05',
            type: 'item',
            //icon:<MdOutlineFeed />,
            url: '/rp01/rp105',
          },
        ],
      },
      {
        id: 'rp02',
        title: 'sidebar.rp02',
        messageId: 'sidebar.rp02',
        type: 'collapse',
        icon: <MdOutlineFactCheck />,
        children: [
          {
            id: 'rp201',
            title: 'sidebar.rp02',
            messageId: 'sidebar.rp02.01',
            type: 'item',
            //icon:<MdOutlineFeaturedPlayList/>,
            url: '/rp02/rp201',
          },
          {
            id: 'rp202',
            title: 'sidebar.rp02',
            messageId: 'sidebar.rp02.02',
            type: 'item',
            //icon:<MdOutlineFeaturedPlayList/>,
            url: '/rp02/rp202',
          },
          {
            id: 'rp203',
            title: 'sidebar.rp02',
            messageId: 'sidebar.rp02.03',
            type: 'item',
            //icon:<MdOutlineFeaturedPlayList/>,
            url: '/rp02/rp203',
          },
          {
            id: 'rp204',
            title: 'sidebar.rp02',
            messageId: 'sidebar.rp02.04',
            type: 'item',
            //icon:<MdOutlineFileOpen/>,
            url: '/rp02/rp204',
          },
          {
            id: 'rp205',
            title: 'sidebar.rp02',
            messageId: 'sidebar.rp02.05',
            type: 'item',
            //icon:<MdOutlineFileOpen/>,
            url: '/rp02/rp205',
          },
        ],
      },

    ],
  },
/*
      {
        id: 'crm',
        title: 'CRM',
        messageId: 'sidebar.app.dashboard.crm',
        type: 'item',
        icon: <RiCustomerService2Line />,
        url: '/dashboards/crm',
      },
      {
        id: 'analytics',
        title: 'Analytics',
        messageId: 'sidebar.app.dashboard.analytics',
        type: 'item',
        icon: <MdOutlineAnalytics />,
        url: '/dashboards/analytics',
      },
      {
        id: 'healthCare',
        title: 'Health Care',
        messageId: 'sidebar.healthCare',
        type: 'item',
        icon: <FaRegHospital />,
        url: '/dashboards/health-care',
      },
      {
        id: 'e-commerce',
        title: 'E-Commerce',
        messageId: 'sidebar.app.dashboard.eCommerce',
        type: 'item',
        icon: <BsCart4 />,
        url: '/dashboards/e-commerce',
      },
      {
        id: 'academy',
        title: 'Academy',
        messageId: 'sidebar.app.dashboard.academy',
        type: 'item',
        icon: <HiOutlineAcademicCap />,
        url: '/dashboards/academy',
      },
      {
        id: 'metrics',
        title: 'Metrics',
        messageId: 'sidebar.app.metrics',
        type: 'item',
        icon: <HiOutlineChartSquareBar />,
        url: '/dashboards/metrics',
      },
      {
        id: 'widgets',
        title: 'Widgets',
        messageId: 'sidebar.app.widgets',
        type: 'item',
        icon: <RiDashboardLine />,
        url: '/dashboards/widgets',
      },
    ],
  },
  {
    id: 'app',
    title: 'Application',
    messageId: 'sidebar.application',
    type: 'group',
    children: [
      {
        id: 'crypto',
        title: 'Crypto',
        messageId: 'sidebar.app.dashboard.crypto',
        type: 'item',
        icon: <BsCurrencyBitcoin />,
        url: '/dashboards/crypto',
      },
      {
        id: 'crm',
        title: 'CRM',
        messageId: 'sidebar.app.dashboard.crm',
        type: 'item',
        icon: <RiCustomerService2Line />,
        url: '/dashboards/crm',
      },
      {
        id: 'analytics',
        title: 'Analytics',
        messageId: 'sidebar.app.dashboard.analytics',
        type: 'item',
        icon: <MdOutlineAnalytics />,
        url: '/dashboards/analytics',
      },
      {
        id: 'healthCare',
        title: 'Health Care',
        messageId: 'sidebar.healthCare',
        type: 'item',
        icon: <FaRegHospital />,
        url: '/dashboards/health-care',
      },
      {
        id: 'e-commerce',
        title: 'E-Commerce',
        messageId: 'sidebar.app.dashboard.eCommerce',
        type: 'item',
        icon: <BsCart4 />,
        url: '/dashboards/e-commerce',
      },
      {
        id: 'academy',
        title: 'Academy',
        messageId: 'sidebar.app.dashboard.academy',
        type: 'item',
        icon: <HiOutlineAcademicCap />,
        url: '/dashboards/academy',
      },
      {
        id: 'metrics',
        title: 'Metrics',
        messageId: 'sidebar.app.metrics',
        type: 'item',
        icon: <HiOutlineChartSquareBar />,
        url: '/dashboards/metrics',
      },
      {
        id: 'widgets',
        title: 'Widgets',
        messageId: 'sidebar.app.widgets',
        type: 'item',
        icon: <RiDashboardLine />,
        url: '/dashboards/widgets',
      },
    ],
  },
  {
    id: 'apps',
    title: 'Apps',
    messageId: 'sidebar.apps',
    type: 'group',
    children: [
      {
        id: 'mail',
        title: 'Mail',
        messageId: 'sidebar.apps.mail',
        type: 'item',
        count: 4,
        icon: 'mail_outline',
        url: '/apps/mail/inbox',
      },
      {
        id: 'todo',
        title: 'ToDo',
        messageId: 'sidebar.apps.todo',
        type: 'item',
        count: 6,
        icon: <RiTodoLine />,
        color: '#48bb78',
        url: '/apps/todo/all',
      },
      {
        id: 'calender',
        title: 'Calender',
        messageId: 'sidebar.apps.calender',
        type: 'item',
        icon: <BiTask />,
        url: '/apps/calender/all',
      },
      {
        id: 'contact',
        title: 'Contact',
        messageId: 'sidebar.apps.contact',
        type: 'item',
        icon: <MdOutlineContactPhone />,
        url: '/apps/contact/folder/all',
      },
      {
        id: 'chat',
        title: 'Chat',
        messageId: 'sidebar.apps.chat',
        type: 'item',
        icon: <BsChatDots />,
        url: '/apps/chat',
      },
      {
        id: 'wall',
        title: 'Wall',
        messageId: 'sidebar.apps.wall',
        type: 'item',
        icon: <CgFeed />,
        url: '/apps/wall',
      },
      {
        id: 'ecommerce',
        title: 'Ecommerce',
        messageId: 'sidebar.ecommerce',
        type: 'collapse',
        icon: <BiCartAlt />,
        children: [
          {
            id: 'products',
            title: 'Products',
            messageId: 'sidebar.ecommerce.products',
            type: 'item',
            url: '/ecommerce/products',
          },
          {
            id: 'product_detail',
            title: 'Product Detail',
            messageId: 'sidebar.ecommerce.productDetail',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'orders',
            title: 'Orders',
            messageId: 'sidebar.ecommerce.orders',
            type: 'item',
            url: '/ecommerce/orders',
          },
          {
            id: 'cart',
            title: 'Cart',
            messageId: 'sidebar.ecommerce.cart',
            type: 'item',
            url: '/ecommerce/cart',
          },
          {
            id: 'checkout',
            title: 'Checkout',
            messageId: 'sidebar.ecommerce.checkout',
            type: 'item',
            url: '/ecommerce/checkout',
          },
          {
            id: 'confirmation',
            title: 'Confirmation',
            messageId: 'sidebar.ecommerce.confirmation',
            type: 'item',
            url: '/ecommerce/confirmation',
          },
          {
            id: 'invoice-1',
            title: 'Invoice 1',
            messageId: 'sidebar.ecommerce.invoice1',
            type: 'item',
            url: '/ecommerce/invoice-1',
          },
          {
            id: 'invoice-2',
            title: 'Invoice 2',
            messageId: 'sidebar.ecommerce.invoice2',
            type: 'item',
            url: '/ecommerce/invoice-2',
          },
        ],
      },
      {
        id: 'admin-ecommerce',
        title: 'Ecommerce Admin',
        messageId: 'sidebar.ecommerceAdmin',
        type: 'collapse',
        icon: <GrUserAdmin />,
        children: [
          {
            id: 'productListing',
            title: 'Product Listing',
            messageId: 'sidebar.ecommerceAdmin.productListing',
            type: 'item',
            url: '/ecommerce/product-listing',
          },
          {
            id: 'addProducts',
            title: 'Add Products',
            messageId: 'sidebar.ecommerceAdmin.addProducts',
            type: 'item',
            url: '/ecommerce/add-products',
          },
          {
            id: 'customers',
            title: 'Customers',
            messageId: 'sidebar.ecommerce.customers',
            type: 'item',
            url: '/ecommerce/customers',
          },
        ],
      },
      {
        id: 'invoice',
        title: 'Invoice',
        messageId: 'sidebar.invoice',
        type: 'collapse',
        icon: <TbFileInvoice />,
        children: [
          {
            id: 'addInvoice',
            title: 'Add Invoices',
            messageId: 'sidebar.invoice.addInvoice',
            type: 'item',
            url: '/invoice/add-invoice',
          },
          {
            id: 'invoices',
            title: 'Invoices',
            messageId: 'sidebar.invoice.home',
            type: 'item',
            url: '/invoice',
          },
          {
            id: 'clients',
            title: 'Clients',
            messageId: 'sidebar.invoice.clients',
            type: 'item',
            url: '/invoice/clients',
          },
          {
            id: 'settings',
            title: 'Settings',
            messageId: 'sidebar.invoice.settings',
            type: 'item',
            url: '/invoice/settings',
          },
        ],
      },
      {
        id: 'blog',
        title: 'Blog',
        messageId: 'sidebar.pages.extraPages.blog',
        type: 'collapse',
        icon: 'rss_feed',
        children: [
          {
            id: 'bloglist',
            title: 'Blog List',
            messageId: 'sidebar.pages.extraPages.blogList',
            type: 'item',
            url: '/extra-pages/blog',
          },
          {
            id: 'blogdetail',
            title: 'Blog Detail',
            messageId: 'sidebar.pages.extraPages.blogDetail',
            type: 'item',
            url: '/extra-pages/blog/blog-details',
          },
          {
            id: 'blogcreate',
            title: 'Create Blog',
            messageId: 'sidebar.pages.extraPages.blogCreate',
            type: 'item',
            url: '/extra-pages/blog/create-blog',
          },
        ],
      },
    ],
  },
  {
    id: 'third-party',
    title: 'Libs',
    messageId: 'sidebar.libs',
    type: 'group',
    children: [
      {
        id: 'google-map',
        title: 'Google Map',
        messageId: 'sidebar.googleMap',
        type: 'item',
        icon: <FiMap />,
        url: '/third-party/google-map',
      },
      {
        id: 'recharts',
        title: 'Recharts',
        messageId: 'sidebar.recharts',
        type: 'collapse',
        icon: 'bar_chart',
        children: [
          {
            id: 'area',
            title: 'Area Chart',
            messageId: 'sidebar.recharts.areaChart',
            type: 'item',
            url: '/third-party/recharts/area',
          },
          {
            id: 'bar',
            title: 'Bar Chart',
            messageId: 'sidebar.recharts.barChart',
            type: 'item',
            url: '/third-party/recharts/bar',
          },
          {
            id: 'composed',
            title: 'Composed Chart',
            messageId: 'sidebar.recharts.composedChart',
            type: 'item',
            url: '/third-party/recharts/composed',
          },
          {
            id: 'composed',
            title: 'Composed Chart',
            messageId: 'sidebar.recharts.composedChart',
            type: 'item',
            url: '/third-party/recharts/composed',
          },
          {
            id: 'line',
            title: 'Line Chart',
            messageId: 'sidebar.recharts.lineChart',
            type: 'item',
            url: '/third-party/recharts/line',
          },
          {
            id: 'pie',
            title: 'Pie Chart',
            messageId: 'sidebar.recharts.pieChart',
            type: 'item',
            url: '/third-party/recharts/pie',
          },
          {
            id: 'radar',
            title: 'Radar Chart',
            messageId: 'sidebar.recharts.radarChart',
            type: 'item',
            url: '/third-party/recharts/radar',
          },
          {
            id: 'radial',
            title: 'Radial Chart',
            messageId: 'sidebar.recharts.radialChart',
            type: 'item',
            url: '/third-party/recharts/radial',
          },
          {
            id: 'scatter',
            title: 'Scatter Chart',
            messageId: 'sidebar.recharts.scatterChart',
            type: 'item',
            url: '/third-party/recharts/scatter',
          },
          {
            id: 'funnel',
            title: 'Funnel Chart',
            messageId: 'sidebar.recharts.funnelChart',
            type: 'item',
            url: '/third-party/recharts/funnel',
          },
          {
            id: 'treemap',
            title: 'Treemap Chart',
            messageId: 'sidebar.recharts.treeChart',
            type: 'item',
            url: '/third-party/recharts/treemap',
          },
        ],
      },
      {
        id: 'filestack',
        title: 'Filestack',
        messageId: 'sidebar.filestack',
        type: 'item',
        icon: <RiFileUploadLine />,
        url: '/third-party/filestack',
      },
      {
        id: 'froala-editor',
        title: 'Froala Editor',
        messageId: 'sidebar.froalaEditor',
        type: 'item',
        icon: <AiOutlineEdit />,
        url: '/third-party/froala-editor',
      },
      {
        id: 'fusion-charts',
        title: 'Fusion Charts',
        messageId: 'sidebar.fusionCharts',
        type: 'item',
        icon: 'bar_chart',
        url: '/third-party/fusion-charts',
      },
      {
        id: 'calendar',
        title: 'Big Calendar',
        messageId: 'sidebar.bigCalender',
        icon: <FaRegCalendarAlt />,
        type: 'item',
        url: '/third-party/calendar',
      },
      {
        id: 'slider',
        title: 'React Slick',
        messageId: 'sidebar.reactSlick',
        icon: <BiCarousel />,
        type: 'item',
        url: '/third-party/slider',
      },
      {
        id: 'react-color',
        title: 'React Color',
        messageId: 'sidebar.reactColor',
        type: 'item',
        icon: 'invert_colors',
        url: '/third-party/react-color',
      },
      {
        id: 'react-dropzone',
        title: 'React Dropzone',
        messageId: 'sidebar.reactDropzone',
        type: 'item',
        icon: 'attach_file',
        url: '/third-party/react-dropzone',
      },
      {
        id: 'react-player',
        title: 'Player',
        messageId: 'sidebar.player',
        type: 'item',
        icon: <DiHtml5Multimedia />,
        url: '/third-party/react-player',
      },
      {
        id: 'timeline',
        title: 'Time Line',
        messageId: 'sidebar.pages.timeLine',
        type: 'item',
        icon: 'timeline',
        url: '/third-party/time-line',
      },
    ],
  },
  {
    id: 'extra-pages',
    title: 'Extra Pages',
    messageId: 'sidebar.pages.extraPages',
    type: 'group',
    children: [
      {
        id: 'account',
        title: 'Account',
        messageId: 'sidebar.pages.extraPages.account',
        type: 'item',
        icon: <MdOutlineManageAccounts />,
        url: '/account/my-profile',
      },
      {
        id: 'about-us',
        title: 'About Us',
        messageId: 'sidebar.pages.extraPages.aboutUs',
        type: 'item',
        icon: <FiUsers />,
        url: '/extra-pages/about-us',
      },
      {
        id: 'contact-us',
        title: 'Contact Us',
        messageId: 'sidebar.pages.extraPages.contactUs',
        type: 'item',
        icon: <MdOutlineContactSupport />,
        url: '/extra-pages/contact-us',
      },
      {
        id: 'portfolio',
        title: 'Portfolio',
        messageId: 'sidebar.pages.extraPages.portfolio',
        type: 'item',
        icon: <BsBriefcase />,
        url: '/extra-pages/portfolio',
      },
      {
        id: 'faq',
        title: 'FAQ',
        messageId: 'sidebar.pages.extraPages.faq',
        type: 'item',
        icon: <BsQuestionDiamond />,
        url: '/extra-pages/faq',
      },
      {
        id: 'pricing',
        title: 'Pricing',
        messageId: 'sidebar.pages.extraPages.pricing',
        type: 'collapse',
        icon: 'attach_money',
        url: '/extra-pages/pricing',
        children: [
          {
            id: 'pricingListing',
            title: 'Pricing Listing',
            messageId: 'sidebar.pages.extraPages.pricingListing',
            type: 'item',
            url: '/extra-pages/pricing-listing',
          },
          {
            id: 'pricingDetail',
            title: 'Pricing Detail',
            messageId: 'sidebar.pages.extraPages.pricingDetail',
            type: 'item',
            url: '/extra-pages/pricing-detail',
          },
        ],
      },
      {
        id: 'user',
        title: 'User Pages',
        messageId: 'sidebar.pages.userPages',
        type: 'collapse',
        icon: <RiShieldUserLine />,
        children: [
          {
            id: 'sign-in-1',
            title: 'SignIn-1',
            messageId: 'sidebar.pages.userPages.signIn1',
            type: 'item',
            url: '/user/sign-in-1',
          },
          {
            id: 'sign-in-2',
            title: 'SignIn-2',
            messageId: 'sidebar.pages.userPages.signIn2',
            type: 'item',
            url: '/user/sign-in-2',
          },
          {
            id: 'sign-up-1',
            title: 'SignUp-1',
            messageId: 'sidebar.pages.userPages.signUp1',
            type: 'item',
            url: '/user/sign-up-1',
          },
          {
            id: 'sign-up-2',
            title: 'SignUp-2',
            messageId: 'sidebar.pages.userPages.signUp2',
            type: 'item',
            url: '/user/sign-up-2',
          },
          {
            id: 'forgot-password-1',
            title: 'Forgot Password-1',
            messageId: 'sidebar.pages.userPages.forgetPassword1',
            type: 'item',
            url: '/user/forgot-password-1',
          },
          {
            id: 'forgot-password-2',
            title: 'Forgot Password-2',
            messageId: 'sidebar.pages.userPages.forgetPassword2',
            type: 'item',
            url: '/user/forgot-password-2',
          },
          {
            id: 'reset-password-1',
            title: 'Reset Password-1',
            messageId: 'sidebar.pages.userPages.resetPassword1',
            type: 'item',
            url: '/user/reset-password-1',
          },
          {
            id: 'reset-password-2',
            title: 'Reset Password-2',
            messageId: 'sidebar.pages.userPages.resetPassword2',
            type: 'item',
            url: '/user/reset-password-2',
          },
          {
            id: 'lock-1',
            title: 'Lock Screen-1',
            messageId: 'sidebar.pages.userPages.lockScreen1',
            type: 'item',
            url: '/user/lock-1',
          },
          {
            id: 'lock-2',
            title: 'Lock Screen-2',
            messageId: 'sidebar.pages.userPages.lockScreen2',
            type: 'item',
            url: '/user/lock-2',
          },
        ],
      },
      {
        id: 'list-type',
        title: 'User List',
        messageId: 'sidebar.pages.userList',
        type: 'collapse',
        icon: <AiOutlineUnorderedList />,
        children: [
          {
            id: 'morden',
            title: 'Modern',
            messageId: 'sidebar.pages.userList.modern',
            type: 'item',
            url: '/list-type/morden',
          },
          {
            id: 'standard',
            title: 'Standard',
            messageId: 'sidebar.pages.userList.standard',
            type: 'item',
            url: '/list-type/standard',
          },
          {
            id: 'flat',
            title: 'Flat',
            messageId: 'sidebar.pages.userList.flat',
            type: 'item',
            url: '/list-type/flat',
          },
        ],
      },
      {
        id: 'error-pages',
        title: 'Error Pages',
        messageId: 'sidebar.pages.errorPages',
        type: 'collapse',
        icon: <BiErrorAlt />,
        children: [
          {
            id: 'error-401',
            title: '402',
            messageId: 'sidebar.pages.errorPages.401',
            type: 'item',
            url: '/error-pages/error-401',
          },
          {
            id: 'error-403',
            title: '403',
            messageId: 'sidebar.pages.errorPages.403',
            type: 'item',
            url: '/error-pages/error-403',
          },
          {
            id: 'error-404',
            title: '404',
            messageId: 'sidebar.pages.errorPages.404',
            type: 'item',
            url: '/error-pages/error-404',
          },
          {
            id: 'error-500',
            title: '500',
            messageId: 'sidebar.pages.errorPages.500',
            type: 'item',
            url: '/error-pages/error-500',
          },
          {
            id: 'error-503',
            title: '503',
            messageId: 'sidebar.pages.errorPages.503',
            type: 'item',
            url: '/error-pages/error-503',
          },
          {
            id: 'maintenance',
            title: 'Maintenance',
            messageId: 'sidebar.pages.errorPages.maintenance',
            type: 'item',
            url: '/error-pages/maintenance',
          },
          {
            id: 'coming-soon',
            title: 'Coming Soon',
            messageId: 'sidebar.pages.errorPages.comingSoon',
            type: 'item',
            url: '/error-pages/coming-soon',
          },
        ],
      },
    ],
  },*/


];
export default routesConfig;
