import { FaRegCalendarAlt, FaRegHospital } from 'react-icons/fa';
import { FiMap, FiUsers } from 'react-icons/fi';
import { HiOutlineAcademicCap, HiOutlineChartSquareBar } from 'react-icons/hi';
import {
  RiCustomerService2Line,
  RiDashboardLine,
  RiFileUploadLine,
  RiShieldUserLine,
  RiTodoLine,
} from 'react-icons/ri';
import { BiCarousel, BiCartAlt, BiErrorAlt, BiTask } from 'react-icons/bi';
import { BsBriefcase, BsCart4, BsChatDots, BsCurrencyBitcoin, BsQuestionDiamond } from 'react-icons/bs';
import { DiHtml5Multimedia } from 'react-icons/di';
import {
  MdOutlineAnalytics,
  MdOutlineContactPhone,
  MdOutlineContactSupport,
  MdOutlineDns,
  MdOutlineManageAccounts,
} from 'react-icons/md';
import { CgFeed } from 'react-icons/cg';
import { GrUserAdmin } from 'react-icons/gr';
import { AiOutlineEdit, AiOutlineUnorderedList } from 'react-icons/ai';
import { TbFileInvoice } from 'react-icons/tb';

const routesConfig = [
  {
    id: 'hr',
    title: 'ระบบบริหารงานบุคลากร',
    messageId: 'sidebar.hr',
    type: 'group',
    children: [
      {
        id: 'hr01',
        title: 'Ecommerce',
        messageId: 'sidebar.hr01',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr101',
            title: 'Products',
            messageId: 'sidebar.hr01.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr102',
            title: 'Product Detail',
            messageId: 'sidebar.hr01.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr103',
            title: 'Orders',
            messageId: 'sidebar.hr01.03',
            type: 'item',
            url: '/hr01/hr103',
          },
          {
            id: 'hr104',
            title: 'Cart',
            messageId: 'sidebar.hr01.04',
            type: 'item',
            url: '/ecommerce/cart',
          },
          {
            id: 'hr105',
            title: 'Checkout',
            messageId: 'sidebar.hr01.05',
            type: 'item',
            url: '/ecommerce/checkout',
          },
          {
            id: 'hr106',
            title: 'Confirmation',
            messageId: 'sidebar.hr01.06',
            type: 'item',
            url: '/ecommerce/confirmation',
          },
        ],
      },
      {
        id: 'hr02',
        title: 'Ecommerce',
        messageId: 'sidebar.hr02',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr201',
            title: 'Products',
            messageId: 'sidebar.hr02.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr202',
            title: 'Product Detail',
            messageId: 'sidebar.hr02.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr203',
            title: 'Orders',
            messageId: 'sidebar.hr02.03',
            type: 'item',
            url: '/ecommerce/orders',
          },
          {
            id: 'hr204',
            title: 'Cart',
            messageId: 'sidebar.hr02.04',
            type: 'item',
            url: '/ecommerce/cart',
          },
          {
            id: 'hr205',
            title: 'Checkout',
            messageId: 'sidebar.hr02.05',
            type: 'item',
            url: '/ecommerce/checkout',
          },
        ],
      },
      {
        id: 'hr03',
        title: 'Ecommerce',
        messageId: 'sidebar.hr03',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr301',
            title: 'Products',
            messageId: 'sidebar.hr03.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr302',
            title: 'Product Detail',
            messageId: 'sidebar.hr03.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr303',
            title: 'Orders',
            messageId: 'sidebar.hr03.03',
            type: 'item',
            url: '/ecommerce/orders',
          },
        ],
      },
      {
        id: 'hr04',
        title: 'Ecommerce',
        messageId: 'sidebar.hr04',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr401',
            title: 'Products',
            messageId: 'sidebar.hr04.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr402',
            title: 'Product Detail',
            messageId: 'sidebar.hr04.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr403',
            title: 'Orders',
            messageId: 'sidebar.hr04.03',
            type: 'item',
            url: '/ecommerce/orders',
          },
        ],
      },
      {
        id: 'hr05',
        title: 'Ecommerce',
        messageId: 'sidebar.hr05',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr501',
            title: 'Products',
            messageId: 'sidebar.hr05.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr502',
            title: 'Product Detail',
            messageId: 'sidebar.hr05.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
        ],
      },
      {
        id: 'hr06',
        title: 'Ecommerce',
        messageId: 'sidebar.hr06',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr601',
            title: 'Products',
            messageId: 'sidebar.hr06.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr602',
            title: 'Product Detail',
            messageId: 'sidebar.hr06.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr603',
            title: 'Orders',
            messageId: 'sidebar.hr06.03',
            type: 'item',
            url: '/ecommerce/orders',
          },
          {
            id: 'hr604',
            title: 'Orders',
            messageId: 'sidebar.hr06.04',
            type: 'item',
            url: '/ecommerce/orders',
          },
        ],
      },
      {
        id: 'hr07',
        title: 'Ecommerce',
        messageId: 'sidebar.hr07',
        type: 'collapse',
        icon: <MdOutlineContactPhone />,
        children: [
          {
            id: 'hr701',
            title: 'Products',
            messageId: 'sidebar.hr07.01',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'hr702',
            title: 'Product Detail',
            messageId: 'sidebar.hr07.02',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
        ],
      },
      {
        id: 'crm',
        title: 'CRM',
        messageId: 'sidebar.app.dashboard.crm',
        type: 'item',
        icon: <RiCustomerService2Line />,
        url: '/dashboards/crm',
      },
      {
        id: 'analytics',
        title: 'Analytics',
        messageId: 'sidebar.app.dashboard.analytics',
        type: 'item',
        icon: <MdOutlineAnalytics />,
        url: '/dashboards/analytics',
      },
      {
        id: 'healthCare',
        title: 'Health Care',
        messageId: 'sidebar.healthCare',
        type: 'item',
        icon: <FaRegHospital />,
        url: '/dashboards/health-care',
      },
      {
        id: 'e-commerce',
        title: 'E-Commerce',
        messageId: 'sidebar.app.dashboard.eCommerce',
        type: 'item',
        icon: <BsCart4 />,
        url: '/dashboards/e-commerce',
      },
      {
        id: 'academy',
        title: 'Academy',
        messageId: 'sidebar.app.dashboard.academy',
        type: 'item',
        icon: <HiOutlineAcademicCap />,
        url: '/dashboards/academy',
      },
      {
        id: 'metrics',
        title: 'Metrics',
        messageId: 'sidebar.app.metrics',
        type: 'item',
        icon: <HiOutlineChartSquareBar />,
        url: '/dashboards/metrics',
      },
      {
        id: 'widgets',
        title: 'Widgets',
        messageId: 'sidebar.app.widgets',
        type: 'item',
        icon: <RiDashboardLine />,
        url: '/dashboards/widgets',
      },
    ],
  },
  {
    id: 'app',
    title: 'Application',
    messageId: 'sidebar.application',
    type: 'group',
    children: [
      {
        id: 'crypto',
        title: 'Crypto',
        messageId: 'sidebar.app.dashboard.crypto',
        type: 'item',
        icon: <BsCurrencyBitcoin />,
        url: '/dashboards/crypto',
      },
      {
        id: 'crm',
        title: 'CRM',
        messageId: 'sidebar.app.dashboard.crm',
        type: 'item',
        icon: <RiCustomerService2Line />,
        url: '/dashboards/crm',
      },
      {
        id: 'analytics',
        title: 'Analytics',
        messageId: 'sidebar.app.dashboard.analytics',
        type: 'item',
        icon: <MdOutlineAnalytics />,
        url: '/dashboards/analytics',
      },
      {
        id: 'healthCare',
        title: 'Health Care',
        messageId: 'sidebar.healthCare',
        type: 'item',
        icon: <FaRegHospital />,
        url: '/dashboards/health-care',
      },
      {
        id: 'e-commerce',
        title: 'E-Commerce',
        messageId: 'sidebar.app.dashboard.eCommerce',
        type: 'item',
        icon: <BsCart4 />,
        url: '/dashboards/e-commerce',
      },
      {
        id: 'academy',
        title: 'Academy',
        messageId: 'sidebar.app.dashboard.academy',
        type: 'item',
        icon: <HiOutlineAcademicCap />,
        url: '/dashboards/academy',
      },
      {
        id: 'metrics',
        title: 'Metrics',
        messageId: 'sidebar.app.metrics',
        type: 'item',
        icon: <HiOutlineChartSquareBar />,
        url: '/dashboards/metrics',
      },
      {
        id: 'widgets',
        title: 'Widgets',
        messageId: 'sidebar.app.widgets',
        type: 'item',
        icon: <RiDashboardLine />,
        url: '/dashboards/widgets',
      },
    ],
  },
  {
    id: 'apps',
    title: 'Apps',
    messageId: 'sidebar.apps',
    type: 'group',
    children: [
      {
        id: 'mail',
        title: 'Mail',
        messageId: 'sidebar.apps.mail',
        type: 'item',
        count: 4,
        icon: 'mail_outline',
        url: '/apps/mail/inbox',
      },
      {
        id: 'todo',
        title: 'ToDo',
        messageId: 'sidebar.apps.todo',
        type: 'item',
        count: 6,
        icon: <RiTodoLine />,
        color: '#48bb78',
        url: '/apps/todo/all',
      },
      {
        id: 'calender',
        title: 'Calender',
        messageId: 'sidebar.apps.calender',
        type: 'item',
        icon: <BiTask />,
        url: '/apps/calender/all',
      },
      {
        id: 'contact',
        title: 'Contact',
        messageId: 'sidebar.apps.contact',
        type: 'item',
        icon: <MdOutlineContactPhone />,
        url: '/apps/contact/folder/all',
      },
      {
        id: 'chat',
        title: 'Chat',
        messageId: 'sidebar.apps.chat',
        type: 'item',
        icon: <BsChatDots />,
        url: '/apps/chat',
      },
      {
        id: 'wall',
        title: 'Wall',
        messageId: 'sidebar.apps.wall',
        type: 'item',
        icon: <CgFeed />,
        url: '/apps/wall',
      },
      {
        id: 'ecommerce',
        title: 'Ecommerce',
        messageId: 'sidebar.ecommerce',
        type: 'collapse',
        icon: <BiCartAlt />,
        children: [
          {
            id: 'products',
            title: 'Products',
            messageId: 'sidebar.ecommerce.products',
            type: 'item',
            url: '/ecommerce/products',
          },
          {
            id: 'product_detail',
            title: 'Product Detail',
            messageId: 'sidebar.ecommerce.productDetail',
            type: 'item',
            url: '/ecommerce/product_detail',
          },
          {
            id: 'orders',
            title: 'Orders',
            messageId: 'sidebar.ecommerce.orders',
            type: 'item',
            url: '/ecommerce/orders',
          },
          {
            id: 'cart',
            title: 'Cart',
            messageId: 'sidebar.ecommerce.cart',
            type: 'item',
            url: '/ecommerce/cart',
          },
          {
            id: 'checkout',
            title: 'Checkout',
            messageId: 'sidebar.ecommerce.checkout',
            type: 'item',
            url: '/ecommerce/checkout',
          },
          {
            id: 'confirmation',
            title: 'Confirmation',
            messageId: 'sidebar.ecommerce.confirmation',
            type: 'item',
            url: '/ecommerce/confirmation',
          },
          {
            id: 'invoice-1',
            title: 'Invoice 1',
            messageId: 'sidebar.ecommerce.invoice1',
            type: 'item',
            url: '/ecommerce/invoice-1',
          },
          {
            id: 'invoice-2',
            title: 'Invoice 2',
            messageId: 'sidebar.ecommerce.invoice2',
            type: 'item',
            url: '/ecommerce/invoice-2',
          },
        ],
      },
      {
        id: 'admin-ecommerce',
        title: 'Ecommerce Admin',
        messageId: 'sidebar.ecommerceAdmin',
        type: 'collapse',
        icon: <GrUserAdmin />,
        children: [
          {
            id: 'productListing',
            title: 'Product Listing',
            messageId: 'sidebar.ecommerceAdmin.productListing',
            type: 'item',
            url: '/ecommerce/product-listing',
          },
          {
            id: 'addProducts',
            title: 'Add Products',
            messageId: 'sidebar.ecommerceAdmin.addProducts',
            type: 'item',
            url: '/ecommerce/add-products',
          },
          {
            id: 'customers',
            title: 'Customers',
            messageId: 'sidebar.ecommerce.customers',
            type: 'item',
            url: '/ecommerce/customers',
          },
        ],
      },
      {
        id: 'invoice',
        title: 'Invoice',
        messageId: 'sidebar.invoice',
        type: 'collapse',
        icon: <TbFileInvoice />,
        children: [
          {
            id: 'addInvoice',
            title: 'Add Invoices',
            messageId: 'sidebar.invoice.addInvoice',
            type: 'item',
            url: '/invoice/add-invoice',
          },
          {
            id: 'invoices',
            title: 'Invoices',
            messageId: 'sidebar.invoice.home',
            type: 'item',
            url: '/invoice',
          },
          {
            id: 'clients',
            title: 'Clients',
            messageId: 'sidebar.invoice.clients',
            type: 'item',
            url: '/invoice/clients',
          },
          {
            id: 'settings',
            title: 'Settings',
            messageId: 'sidebar.invoice.settings',
            type: 'item',
            url: '/invoice/settings',
          },
        ],
      },
      {
        id: 'blog',
        title: 'Blog',
        messageId: 'sidebar.pages.extraPages.blog',
        type: 'collapse',
        icon: 'rss_feed',
        children: [
          {
            id: 'bloglist',
            title: 'Blog List',
            messageId: 'sidebar.pages.extraPages.blogList',
            type: 'item',
            url: '/extra-pages/blog',
          },
          {
            id: 'blogdetail',
            title: 'Blog Detail',
            messageId: 'sidebar.pages.extraPages.blogDetail',
            type: 'item',
            url: '/extra-pages/blog/blog-details',
          },
          {
            id: 'blogcreate',
            title: 'Create Blog',
            messageId: 'sidebar.pages.extraPages.blogCreate',
            type: 'item',
            url: '/extra-pages/blog/create-blog',
          },
        ],
      },
    ],
  },
  {
    id: 'third-party',
    title: 'Libs',
    messageId: 'sidebar.libs',
    type: 'group',
    children: [
      {
        id: 'google-map',
        title: 'Google Map',
        messageId: 'sidebar.googleMap',
        type: 'item',
        icon: <FiMap />,
        url: '/third-party/google-map',
      },
      {
        id: 'recharts',
        title: 'Recharts',
        messageId: 'sidebar.recharts',
        type: 'collapse',
        icon: 'bar_chart',
        children: [
          {
            id: 'area',
            title: 'Area Chart',
            messageId: 'sidebar.recharts.areaChart',
            type: 'item',
            url: '/third-party/recharts/area',
          },
          {
            id: 'bar',
            title: 'Bar Chart',
            messageId: 'sidebar.recharts.barChart',
            type: 'item',
            url: '/third-party/recharts/bar',
          },
          {
            id: 'composed',
            title: 'Composed Chart',
            messageId: 'sidebar.recharts.composedChart',
            type: 'item',
            url: '/third-party/recharts/composed',
          },
          {
            id: 'composed',
            title: 'Composed Chart',
            messageId: 'sidebar.recharts.composedChart',
            type: 'item',
            url: '/third-party/recharts/composed',
          },
          {
            id: 'line',
            title: 'Line Chart',
            messageId: 'sidebar.recharts.lineChart',
            type: 'item',
            url: '/third-party/recharts/line',
          },
          {
            id: 'pie',
            title: 'Pie Chart',
            messageId: 'sidebar.recharts.pieChart',
            type: 'item',
            url: '/third-party/recharts/pie',
          },
          {
            id: 'radar',
            title: 'Radar Chart',
            messageId: 'sidebar.recharts.radarChart',
            type: 'item',
            url: '/third-party/recharts/radar',
          },
          {
            id: 'radial',
            title: 'Radial Chart',
            messageId: 'sidebar.recharts.radialChart',
            type: 'item',
            url: '/third-party/recharts/radial',
          },
          {
            id: 'scatter',
            title: 'Scatter Chart',
            messageId: 'sidebar.recharts.scatterChart',
            type: 'item',
            url: '/third-party/recharts/scatter',
          },
          {
            id: 'funnel',
            title: 'Funnel Chart',
            messageId: 'sidebar.recharts.funnelChart',
            type: 'item',
            url: '/third-party/recharts/funnel',
          },
          {
            id: 'treemap',
            title: 'Treemap Chart',
            messageId: 'sidebar.recharts.treeChart',
            type: 'item',
            url: '/third-party/recharts/treemap',
          },
        ],
      },
      {
        id: 'filestack',
        title: 'Filestack',
        messageId: 'sidebar.filestack',
        type: 'item',
        icon: <RiFileUploadLine />,
        url: '/third-party/filestack',
      },
      {
        id: 'froala-editor',
        title: 'Froala Editor',
        messageId: 'sidebar.froalaEditor',
        type: 'item',
        icon: <AiOutlineEdit />,
        url: '/third-party/froala-editor',
      },
      {
        id: 'fusion-charts',
        title: 'Fusion Charts',
        messageId: 'sidebar.fusionCharts',
        type: 'item',
        icon: 'bar_chart',
        url: '/third-party/fusion-charts',
      },
      {
        id: 'calendar',
        title: 'Big Calendar',
        messageId: 'sidebar.bigCalender',
        icon: <FaRegCalendarAlt />,
        type: 'item',
        url: '/third-party/calendar',
      },
      {
        id: 'slider',
        title: 'React Slick',
        messageId: 'sidebar.reactSlick',
        icon: <BiCarousel />,
        type: 'item',
        url: '/third-party/slider',
      },
      {
        id: 'react-color',
        title: 'React Color',
        messageId: 'sidebar.reactColor',
        type: 'item',
        icon: 'invert_colors',
        url: '/third-party/react-color',
      },
      {
        id: 'react-dropzone',
        title: 'React Dropzone',
        messageId: 'sidebar.reactDropzone',
        type: 'item',
        icon: 'attach_file',
        url: '/third-party/react-dropzone',
      },
      {
        id: 'react-player',
        title: 'Player',
        messageId: 'sidebar.player',
        type: 'item',
        icon: <DiHtml5Multimedia />,
        url: '/third-party/react-player',
      },
      {
        id: 'timeline',
        title: 'Time Line',
        messageId: 'sidebar.pages.timeLine',
        type: 'item',
        icon: 'timeline',
        url: '/third-party/time-line',
      },
    ],
  },
  {
    id: 'extra-pages',
    title: 'Extra Pages',
    messageId: 'sidebar.pages.extraPages',
    type: 'group',
    children: [
      {
        id: 'account',
        title: 'Account',
        messageId: 'sidebar.pages.extraPages.account',
        type: 'item',
        icon: <MdOutlineManageAccounts />,
        url: '/account/my-profile',
      },
      {
        id: 'about-us',
        title: 'About Us',
        messageId: 'sidebar.pages.extraPages.aboutUs',
        type: 'item',
        icon: <FiUsers />,
        url: '/extra-pages/about-us',
      },
      {
        id: 'contact-us',
        title: 'Contact Us',
        messageId: 'sidebar.pages.extraPages.contactUs',
        type: 'item',
        icon: <MdOutlineContactSupport />,
        url: '/extra-pages/contact-us',
      },
      {
        id: 'portfolio',
        title: 'Portfolio',
        messageId: 'sidebar.pages.extraPages.portfolio',
        type: 'item',
        icon: <BsBriefcase />,
        url: '/extra-pages/portfolio',
      },
      {
        id: 'faq',
        title: 'FAQ',
        messageId: 'sidebar.pages.extraPages.faq',
        type: 'item',
        icon: <BsQuestionDiamond />,
        url: '/extra-pages/faq',
      },
      {
        id: 'pricing',
        title: 'Pricing',
        messageId: 'sidebar.pages.extraPages.pricing',
        type: 'collapse',
        icon: 'attach_money',
        url: '/extra-pages/pricing',
        children: [
          {
            id: 'pricingListing',
            title: 'Pricing Listing',
            messageId: 'sidebar.pages.extraPages.pricingListing',
            type: 'item',
            url: '/extra-pages/pricing-listing',
          },
          {
            id: 'pricingDetail',
            title: 'Pricing Detail',
            messageId: 'sidebar.pages.extraPages.pricingDetail',
            type: 'item',
            url: '/extra-pages/pricing-detail',
          },
        ],
      },
      {
        id: 'user',
        title: 'User Pages',
        messageId: 'sidebar.pages.userPages',
        type: 'collapse',
        icon: <RiShieldUserLine />,
        children: [
          {
            id: 'sign-in-1',
            title: 'SignIn-1',
            messageId: 'sidebar.pages.userPages.signIn1',
            type: 'item',
            url: '/user/sign-in-1',
          },
          {
            id: 'sign-in-2',
            title: 'SignIn-2',
            messageId: 'sidebar.pages.userPages.signIn2',
            type: 'item',
            url: '/user/sign-in-2',
          },
          {
            id: 'sign-up-1',
            title: 'SignUp-1',
            messageId: 'sidebar.pages.userPages.signUp1',
            type: 'item',
            url: '/user/sign-up-1',
          },
          {
            id: 'sign-up-2',
            title: 'SignUp-2',
            messageId: 'sidebar.pages.userPages.signUp2',
            type: 'item',
            url: '/user/sign-up-2',
          },
          {
            id: 'forgot-password-1',
            title: 'Forgot Password-1',
            messageId: 'sidebar.pages.userPages.forgetPassword1',
            type: 'item',
            url: '/user/forgot-password-1',
          },
          {
            id: 'forgot-password-2',
            title: 'Forgot Password-2',
            messageId: 'sidebar.pages.userPages.forgetPassword2',
            type: 'item',
            url: '/user/forgot-password-2',
          },
          {
            id: 'reset-password-1',
            title: 'Reset Password-1',
            messageId: 'sidebar.pages.userPages.resetPassword1',
            type: 'item',
            url: '/user/reset-password-1',
          },
          {
            id: 'reset-password-2',
            title: 'Reset Password-2',
            messageId: 'sidebar.pages.userPages.resetPassword2',
            type: 'item',
            url: '/user/reset-password-2',
          },
          {
            id: 'lock-1',
            title: 'Lock Screen-1',
            messageId: 'sidebar.pages.userPages.lockScreen1',
            type: 'item',
            url: '/user/lock-1',
          },
          {
            id: 'lock-2',
            title: 'Lock Screen-2',
            messageId: 'sidebar.pages.userPages.lockScreen2',
            type: 'item',
            url: '/user/lock-2',
          },
        ],
      },
      {
        id: 'list-type',
        title: 'User List',
        messageId: 'sidebar.pages.userList',
        type: 'collapse',
        icon: <AiOutlineUnorderedList />,
        children: [
          {
            id: 'morden',
            title: 'Modern',
            messageId: 'sidebar.pages.userList.modern',
            type: 'item',
            url: '/list-type/morden',
          },
          {
            id: 'standard',
            title: 'Standard',
            messageId: 'sidebar.pages.userList.standard',
            type: 'item',
            url: '/list-type/standard',
          },
          {
            id: 'flat',
            title: 'Flat',
            messageId: 'sidebar.pages.userList.flat',
            type: 'item',
            url: '/list-type/flat',
          },
        ],
      },
      {
        id: 'error-pages',
        title: 'Error Pages',
        messageId: 'sidebar.pages.errorPages',
        type: 'collapse',
        icon: <BiErrorAlt />,
        children: [
          {
            id: 'error-401',
            title: '402',
            messageId: 'sidebar.pages.errorPages.401',
            type: 'item',
            url: '/error-pages/error-401',
          },
          {
            id: 'error-403',
            title: '403',
            messageId: 'sidebar.pages.errorPages.403',
            type: 'item',
            url: '/error-pages/error-403',
          },
          {
            id: 'error-404',
            title: '404',
            messageId: 'sidebar.pages.errorPages.404',
            type: 'item',
            url: '/error-pages/error-404',
          },
          {
            id: 'error-500',
            title: '500',
            messageId: 'sidebar.pages.errorPages.500',
            type: 'item',
            url: '/error-pages/error-500',
          },
          {
            id: 'error-503',
            title: '503',
            messageId: 'sidebar.pages.errorPages.503',
            type: 'item',
            url: '/error-pages/error-503',
          },
          {
            id: 'maintenance',
            title: 'Maintenance',
            messageId: 'sidebar.pages.errorPages.maintenance',
            type: 'item',
            url: '/error-pages/maintenance',
          },
          {
            id: 'coming-soon',
            title: 'Coming Soon',
            messageId: 'sidebar.pages.errorPages.comingSoon',
            type: 'item',
            url: '/error-pages/coming-soon',
          },
        ],
      },
    ],
  },
];
export default routesConfig;
